export type ComponentStyleSpecStatus = "currently-used" | "defined-but-unused";

export interface ComponentStyleValue {
  label: string;
  note?: string;
  value: string;
}

export interface ComponentStyleSource {
  file: string;
  note?: string;
}

export interface ComponentStyleSpec {
  description: string;
  group: string;
  id: string;
  name: string;
  note?: string;
  selector?: string;
  sources: ComponentStyleSource[];
  status: ComponentStyleSpecStatus;
  values: ComponentStyleValue[];
}

export const COMPONENT_STYLE_SPECS: ComponentStyleSpec[] = [
  {
    id: "chip",
    name: "Chip",
    group: "칩",
    status: "currently-used",
    description: "일반 목적의 공용 product chip입니다.",
    selector: "src/components/system/Chip.tsx root slot / span",
    sources: [
      { file: "src/components/system/Chip.tsx", note: "size, tone, variant, icon slot API가 여기서 정의됩니다." },
      { file: "src/constants/designTokens.ts", note: "chip size와 semantic tone token map이 있습니다." },
      { file: "src/styles/design-system.css", note: "tb-chip base shell, focus ring, chip size CSS 변수가 정의됩니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "align-items", value: "center" },
      { label: "border-radius", value: "9999px", note: "product-level pill radius" },
      { label: "font-weight", value: "600", note: "semantic / source tag chip 기본 무게" },
      { label: "size xs", value: "font 10px, icon 12px, gap 4px, px 8px, py 4px" },
      { label: "size sm", value: "font 11px, icon 12px, gap 6px, px 10px, py 6px" },
      { label: "size md", value: "font 12px, icon 14px, gap 8px, px 12px, py 8px" },
      { label: "neutral soft", value: "surface-muted / border-default / text-muted" },
      { label: "success soft", value: "success-soft / success-soft / success" },
      { label: "warning soft", value: "warning-soft / warning-soft / warning" },
      { label: "accent solid", value: "text-primary / text-primary / text-inverse" },
      { label: "variants", value: "soft, outline, solid, text" },
      { label: "icon support", value: "leadingIcon / trailingIcon" },
      { label: "background token override", value: "backgroundColorToken", note: "tone background 대신 surface token을 직접 주입할 수 있습니다." },
      { label: "composition", value: "asChild", note: "a, button, span에 같은 chip shell을 적용" },
    ],
  },
  {
    id: "taste-chip",
    name: "TasteChip",
    group: "칩",
    status: "currently-used",
    description: "현재 앱의 미각 포인트 칩입니다.",
    selector: "src/components/system/TasteChip.tsx root span className",
    sources: [
      { file: "src/components/system/TasteChip.tsx", note: "루트와 텍스트 스타일이 여기서 정의됩니다." },
      { file: "src/constants/tasteColors.ts", note: "taste value 강조 컬러를 계산합니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "align-items", value: "center" },
      { label: "gap", value: "4px", note: "`gap-1`" },
      { label: "border-radius", value: "9999px", note: "`rounded-full`" },
      { label: "border", value: "1px solid taste.palette.tintSoftBorder", note: "neutral tone은 border-strong" },
      { label: "background-color", value: "taste.palette.tintSoft", note: "neutral tone은 surface-muted" },
      { label: "padding-inline", value: "8px", note: "`px-2`" },
      { label: "padding-block", value: "4px", note: "`py-1`" },
      { label: "font-size", value: "10px", note: "`text-[10px]`" },
      { label: "font-weight", value: "500", note: "`font-medium`" },
      { label: "label color", value: "var(--tb-color-text-primary)", note: "neutral tone은 text-tertiary" },
      { label: "value font-weight", value: "600", note: "`font-semibold`" },
      { label: "value color", value: "getTasteColor(taste)", note: "taste별 accent 컬러" },
      { label: "tone", value: "taste / neutral", note: "미각과 직접 관련 없는 메타 칩은 neutral tone 사용" },
    ],
  },
  {
    id: "tcs-badge",
    name: "TCSBadge",
    group: "배지",
    status: "currently-used",
    description: "홈 다이닝 준비 카드와 레거시 히스토리 카드 상단에 쓰이는 gradient TCS 배지입니다.",
    selector: ".tb-tcs-badge",
    sources: [
      {
        file: "src/components/system/TCSBadge.tsx",
        note: "disabled state는 var(--tb-color-surface-disabled) 배경을 사용합니다.",
      },
      { file: "src/imports/Home.tsx", note: "레거시 히스토리 카드에서도 같은 공용 컴포넌트를 사용합니다." },
      { file: "DESIGN.md", note: "현재 시스템의 배지 계층과 tone 기준을 정의합니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "align-items", value: "center" },
      { label: "border-radius", value: "6px", note: "`rounded-[6px]`" },
      { label: "padding", value: "2px 6px", note: "`px-[6px] py-[2px]`" },
      { label: "font-size", value: "10px", note: "`text-[10px]`" },
      { label: "font-weight", value: "700", note: "`font-bold`" },
      { label: "line-height", value: "var(--tb-line-height-normal)" },
      { label: "text color", value: "#FFFFFF" },
      {
        label: "background",
        value: "linear-gradient(135deg, weighted taste.light stops with blended transitions ...)",
        note: "history.adjustments의 `change` 절대값 비율만큼 각 미각 light palette 구간이 넓어지고, 각 색은 white 25% mix로 한 단계 더 밝게 처리됩니다.",
      },
      {
        label: "box-shadow",
        value: "0 2px 8px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.1), 1px 1px 2px rgba(0,0,0,0.1), inset 0 1px 1px rgba(255,255,255,0.5), inset 1px 0 1px rgba(255,255,255,0.5), inset 0 -1px 1px rgba(0,0,0,0.1), inset -1px 0 1px rgba(0,0,0,0.1)",
      },
      {
        label: "disabled state",
        value: "background var(--tb-color-surface-disabled) / text color 유지 / elevated shadow 유지",
      },
    ],
  },
  {
    id: "status-chip",
    name: "StatusChip",
    group: "배지",
    status: "currently-used",
    description: "예약 상태와 진행 상태를 표시하는 칩입니다.",
    selector: ".tb-status-chip",
    sources: [
      { file: "src/imports/Home.tsx", note: "홈 탭 TCS 배지가 시각 기준이 되는 원형입니다." },
      {
        file: "src/components/system/StatusChip.tsx",
        note: "기본 스타일은 CSS 토큰을 따르고, 필요 시 backgroundColor / color prop으로 override합니다.",
      },
      { file: "src/styles/design-system.css", note: "기본 radius, padding, text style이 여기서 정의됩니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "align-items", value: "center" },
      { label: "justify-content", value: "center" },
      { label: "width", value: "fit-content" },
      { label: "max-width", value: "100%" },
      { label: "align-self", value: "flex-start" },
      { label: "border-radius", value: "var(--tb-radius-6)" },
      { label: "padding", value: "var(--tb-space-2) var(--tb-space-6)" },
      { label: "background-color", value: "var(--tb-color-surface-muted)", note: "prop override 가능" },
      { label: "text color", value: "var(--tb-color-text-tertiary)", note: "prop override 가능" },
      { label: "font-size", value: "var(--tb-font-size-10)" },
      { label: "font-weight", value: "var(--tb-font-weight-semibold)" },
      { label: "line-height", value: "var(--tb-line-height-normal)" },
      { label: "white-space", value: "nowrap" },
    ],
  },
  {
    id: "outline-badge",
    name: "OutlineBadge",
    group: "배지",
    status: "currently-used",
    description: "프로필 단계와 작은 상태 라벨에 쓰이는 외곽선 배지입니다.",
    selector: ".tb-outline-badge",
    sources: [
      { file: "src/components/system/OutlineBadge.tsx" },
      { file: "src/styles/design-system.css", note: "border, radius, font, padding 정의" },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "align-items", value: "center" },
      { label: "justify-content", value: "center" },
      { label: "border", value: "1px solid var(--tb-color-text-tertiary)" },
      { label: "border-radius", value: "var(--tb-radius-6)" },
      { label: "padding", value: "var(--tb-space-2) var(--tb-space-8)" },
      { label: "text color", value: "var(--tb-color-text-tertiary)" },
      { label: "font-size", value: "var(--tb-font-size-12)" },
      { label: "font-weight", value: "var(--tb-font-weight-semibold)" },
      { label: "line-height", value: "var(--tb-line-height-normal)" },
    ],
  },
  {
    id: "step-badge",
    name: "StepBadge",
    group: "배지",
    status: "currently-used",
    description: "플로우 진행 단계를 `1 / 7`처럼 보여주는 아웃라인 기반 배지입니다.",
    selector: "src/components/system/StepBadge.tsx > .tb-outline-badge",
    sources: [
      { file: "src/components/system/StepBadge.tsx", note: "currentIndex/currentStep를 사람이 읽기 쉬운 분리형 숫자와 슬래시 구조로 렌더링합니다." },
      { file: "src/components/system/OutlineBadge.tsx", note: "배지 shell의 border, radius, font 규칙을 재사용합니다." },
      { file: "src/pages/PreferenceIntakeScreen.tsx", note: "사전 조사 질문 헤더 우측에서 사용됩니다." },
      { file: "src/components/measurement/CalibrationQuestionHeader.tsx", note: "guided measurement-style 질문 헤더 우측에서 사용됩니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "align-items", value: "center" },
      { label: "shrink", value: "0", note: "flex row 안에서 폭이 줄어들지 않도록 유지" },
      { label: "structure", value: "step / total", note: "숫자, 슬래시, 숫자를 분리된 span으로 렌더링" },
      { label: "slash spacing", value: "4px + 4px", note: "`mx-1`" },
      { label: "slash color", value: "var(--tb-color-text-muted)" },
      { label: "base shell", value: "OutlineBadge" },
    ],
  },
  {
    id: "primary-button",
    name: "PrimaryButton",
    group: "버튼",
    status: "currently-used",
    description: "메인 앱에서 실제로 가장 많이 쓰는 CTA 버튼입니다.",
    selector: ".tb-primary-button",
    sources: [
      { file: "src/components/system/PrimaryButton.tsx", note: "compact, disabled, fullWidth variant가 여기서 갈립니다." },
      { file: "src/styles/design-system.css", note: "공통 크기, 색상, shadow, transition 정의" },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "width", value: "100%", note: "fullWidth=false면 `w-auto` override" },
      { label: "height", value: "var(--tb-size-primary-button-height)" },
      { label: "padding-inline", value: "var(--tb-space-16)" },
      { label: "border-radius", value: "var(--tb-radius-10)" },
      { label: "background-color", value: "var(--tb-color-text-primary)" },
      { label: "text color", value: "var(--tb-color-text-inverse)" },
      { label: "font-size", value: "var(--tb-font-size-14)" },
      { label: "font-weight", value: "var(--tb-font-weight-medium)" },
      { label: "shadow", value: "var(--tb-shadow-button)" },
      { label: "active scale", value: "var(--tb-motion-scale-press)" },
      { label: "compact size", value: "min-height 40px, px 16px, py 8px, font-size 12px, font-weight 600, shadow none" },
      { label: "disabled state", value: "background var(--tb-color-surface-disabled), color var(--tb-color-text-disabled), shadow none" },
    ],
  },
  {
    id: "flow-bottom-cta",
    name: "FlowBottomCta",
    group: "버튼",
    status: "currently-used",
    description: "온보딩과 미각 측정, 그리고 여러 flow screen의 하단 CTA shell입니다.",
    selector: "src/components/system/FlowBottomCta.tsx root div",
    sources: [
      { file: "src/components/system/FlowBottomCta.tsx", note: "bottom fade, button, optional top slot / helper copy 조합이 여기 있습니다." },
      { file: "src/components/system/PrimaryButton.tsx", note: "실제 primary action은 PrimaryButton으로 렌더링합니다." },
      { file: "src/styles/design-system.css", note: "bottom fade, safe area, spacing, button height 토큰을 공유합니다." },
    ],
    values: [
      { label: "position", value: "absolute inset-x-0 bottom-0", note: "flow screen bottom anchor" },
      { label: "layout", value: "flex justify-center" },
      { label: "max width", value: "var(--tb-layout-screen-max-width)" },
      { label: "shell background", value: "tb-bottom-fade" },
      { label: "min-height", value: "var(--tb-size-bottom-fade-min-height)" },
      { label: "padding-inline", value: "20px", note: "`px-5`" },
      { label: "padding-bottom", value: "40px + safe area", note: "`pb-10` + `var(--tb-safe-area-bottom)`" },
      { label: "primary action", value: "PrimaryButton" },
      { label: "top slot", value: "optional", note: "step indicator or flow status" },
      { label: "supporting copy", value: "optional", note: "helper text or secondary action" },
    ],
  },
  {
    id: "flow-step-cta",
    name: "FlowStepCta",
    group: "버튼",
    status: "currently-used",
    description: "온보딩과 미각 측정 플로우가 공통으로 쓰는 step indicator + CTA footer입니다.",
    selector: "src/components/system/FlowStepCta.tsx root div",
    sources: [
      { file: "src/components/system/FlowStepCta.tsx", note: "표준 step footer layout과 gradient fade, button spacing이 여기서 정해집니다." },
      { file: "src/components/system/PrimaryButton.tsx", note: "하단 primary action 버튼을 렌더링합니다." },
      { file: "src/components/system/StepIndicator.tsx", note: "진행 단계 점 표시를 렌더링합니다." },
      { file: "src/pages/TasteMeasurementScreen.tsx", note: "미각 측정에서는 active dot만 taste palette.main으로 강조하고 inactive dot은 neutral gray를 유지합니다." },
    ],
    values: [
      { label: "position", value: "absolute inset-x-0 bottom-0", note: "flow screen bottom anchor" },
      { label: "max width", value: "var(--tb-layout-screen-max-width)" },
      { label: "content shell", value: "relative flex min-h-[140px] w-full flex-col items-center justify-end px-5" },
      { label: "footer fade", value: "FlowBottomCta shell gradient to transparent", note: "same footer shell as onboarding" },
      { label: "indicator spacing", value: "margin-bottom 32px", note: "indicator block above the CTA" },
      { label: "button layout", value: "single primary / optional split CTA", note: "secondaryButtonLabel + onSecondaryButtonAction이 있으면 좌우 분할 CTA로 렌더링합니다." },
      { label: "indicator color", value: "default neutral / optional taste-aware active", note: "measurement passes palette.main for the active dot and keeps inactive dots gray" },
    ],
  },
  {
    id: "section-card",
    name: "SectionCard",
    group: "카드",
    status: "currently-used",
    description: "현재 앱 공용 카드 셸입니다.",
    selector: ".tb-section-card / .tb-section-card__body",
    sources: [
      { file: "src/components/SectionCard.tsx", note: "interactive default 조건과 body wrapper 구조" },
      { file: "src/styles/design-system.css", note: "radius, background, hover, body gap/padding 정의" },
    ],
    values: [
      { label: "width", value: "100%" },
      { label: "border-radius", value: "var(--tb-radius-20)" },
      { label: "background-color", value: "var(--tb-color-surface-card)" },
      { label: "hover background", value: "var(--tb-color-surface-card-hover)" },
      { label: "hover shadow", value: "var(--tb-shadow-strong)" },
      { label: "hover translate", value: "translateY(-4px)", note: "interactive일 때만 적용" },
      { label: "active transform", value: "scale(0.99) translateY(-4px)", note: "interactive일 때만 적용" },
      { label: "body display", value: "flex column" },
      { label: "body gap", value: "var(--tb-space-12)" },
      { label: "body padding", value: "var(--tb-space-12)" },
      { label: "interactive default", value: "hoverEffect는 onClick이 있을 때 기본 true" },
      { label: "transition", value: "background-color, box-shadow, transform" },
    ],
  },
  {
    id: "taste-tint-card",
    name: "TasteTintCard",
    group: "카드",
    status: "currently-used",
    description: "정사각형 미각 해석 카드입니다. 맛별 tint surface 위에 결과와 해석을 같이 보여줍니다.",
    selector: "src/components/system/TasteTintCard.tsx root",
    sources: [
      { file: "src/components/system/TasteTintCard.tsx", note: "ChefMatchCard와 같은 정사각형 카드 리듬을 공유하는 공용 미각 해석 카드입니다." },
      { file: "src/components/system/TasteTintCardList.tsx", note: "grid 전용 카드 배치 래퍼입니다." },
      { file: "src/pages/TasteSurveyResultScreen.tsx", note: "설문 기반 starter result 화면의 해석 카드에서 사용됩니다." },
      { file: "src/pages/AnalysisPage.tsx", note: "분석 화면의 세부 분석 카드 스트립에서 실제로 사용됩니다." },
    ],
    values: [
      { label: "display", value: "flex column" },
      { label: "size", value: "132px x 132px" },
      { label: "border-radius", value: "20px" },
      { label: "padding", value: "12px", note: "`p-3`" },
      { label: "background-color", value: "taste.palette.tintSurface" },
      { label: "border", value: "1px solid getTasteTint(taste.label, 0.18)" },
      { label: "leading box", value: "48px x 48px / radius 8px", note: "상단 좌측 고정 박스, 그림자 없음" },
      { label: "title font", value: "14px / 700" },
      { label: "description font", value: "10px / 400" },
      { label: "detail font", value: "10px / 600" },
      { label: "text layout", value: "ChefMatchCard와 동일", note: "상단 48px 박스 + 하단 grow 영역 + title/meta/bottom label" },
      { label: "interactive state", value: "optional", note: "onClick이 있으면 hover lift와 press scale 적용" },
    ],
  },
  {
    id: "card-scroll-list",
    name: "CardScrollList",
    group: "카드",
    status: "currently-used",
    description: "셰프 매칭과 세부 분석처럼 가로로 넘겨보는 카드 스트립을 위한 공용 스크롤 래퍼입니다.",
    selector: "src/components/system/CardScrollList.tsx root div",
    sources: [
      { file: "src/components/system/CardScrollList.tsx", note: "가로 스크롤 카드 스트립의 outer / inner 래퍼를 정의합니다." },
      { file: "src/components/home/HomeCards.tsx", note: "홈 셰프 매칭 스트립의 실제 배치에서 사용됩니다." },
      { file: "src/pages/AnalysisPage.tsx", note: "분석 화면의 세부 분석 카드 스트립에서 사용됩니다." },
      { file: "src/pages/AnalysisPage.tsx", note: "분석 화면의 세부 분석 카드 스트립에서 사용됩니다." },
    ],
    values: [
      { label: "outer display", value: "block / relative" },
      { label: "outer width", value: "calc(100% + 40px)" },
      { label: "outer margin-inline", value: "-20px" },
      { label: "outer overflow-x", value: "auto" },
      { label: "scrollbar", value: "no-scrollbar" },
      { label: "inner display", value: "flex" },
      { label: "inner gap", value: "10px", note: "`gap-[10px]`" },
      { label: "inner padding-inline", value: "20px", note: "`px-[20px]`" },
      { label: "inner padding-top", value: "8px", note: "`pt-2`" },
      { label: "inner padding-bottom", value: "16px", note: "`pb-4`" },
      { label: "align-items", value: "flex-start" },
      { label: "usage", value: "home chef matching / result detail analysis / analysis detail strip" },
    ],
  },
  {
    id: "page-section",
    name: "PageSection",
    group: "카드",
    status: "currently-used",
    description: "섹션 타이틀과 카드 스택을 함께 묶는 공용 레이아웃 래퍼입니다.",
    selector: "src/components/system/PageSection.tsx root div",
    sources: [
      { file: "src/components/system/PageSection.tsx", note: "title, titleAs, contentClassName을 받아 섹션 구조를 통일합니다." },
      { file: "src/components/system/SectionTitle.tsx", note: "섹션 타이틀의 실제 타이포그래피를 담당합니다." },
      { file: "src/pages/AnalysisPage.tsx", note: "나의 미각, 세부 분석, 인사이트 섹션에 실제로 연결되어 있습니다." },
    ],
    values: [
      { label: "layout", value: "flex column" },
      { label: "stack gap", value: "var(--tb-layout-card-stack-gap)", note: "기본값 12px / gap-3" },
      { label: "title component", value: "SectionTitle" },
      { label: "default title size", value: "lg = 18px / md = 16px" },
      { label: "content stack rule", value: "stacked cards should use flex/grid gap-3", note: "contentClassName으로 명시" },
      { label: "usage", value: "main tabs section title + card stack rhythm" },
    ],
  },
  {
    id: "flow-header-block",
    name: "FlowHeaderBlock",
    group: "카드",
    status: "currently-used",
    description: "사전 조사와 미각 설문 intro에서 배지 행과 title / description 블록을 묶는 공통 header block입니다.",
    selector: "src/components/system/FlowHeaderBlock.tsx root div",
    sources: [
      { file: "src/components/system/FlowHeaderBlock.tsx", note: "topLeft/topRight 슬롯과 title/description stack을 한곳에서 정의합니다." },
      { file: "src/pages/PreferenceIntakeScreen.tsx", note: "사전 조사 상단에서 step badge와 함께 사용됩니다." },
      { file: "src/pages/TasteSurveyIntroScreen.tsx", note: "미각 설문 intro 상단에서 dual outline badges와 함께 사용됩니다." },
    ],
    values: [
      { label: "layout", value: "flex column" },
      { label: "outer stack gap", value: "var(--tb-layout-card-stack-gap)", note: "`tb-card-stack`" },
      { label: "top row", value: "flex items-center justify-between gap-3" },
      { label: "left slot", value: "min-width 0", note: "badge or text can expand without forcing overflow" },
      { label: "right slot", value: "shrink-0" },
      { label: "title stack gap", value: "8px", note: "`gap-2`" },
      { label: "title font", value: "SectionTitle" },
      { label: "description font", value: "14px / relaxed / subtle" },
      { label: "title line handling", value: "whitespace-pre-line when multiline" },
    ],
  },
  {
    id: "taste-measurement-mini-cta",
    name: "TasteMeasurementMiniCta",
    group: "앱 전용",
    status: "currently-used",
    description: "분석, 예약, 프로필에서 재사용되는 인라인 CTA 카드입니다.",
    selector: "src/components/measurement/TasteMeasurementMiniCta.tsx root div",
    sources: [
      { file: "src/components/measurement/TasteMeasurementMiniCta.tsx", note: "tone별 root, icon, typography, spacing이 모두 여기 있습니다." },
      { file: "src/components/system/PrimaryButton.tsx", note: "버튼은 compact PrimaryButton을 사용합니다." },
    ],
    values: [
      { label: "border-radius", value: "var(--tb-radius-20)" },
      { label: "border", value: "1px solid", note: "tone에 따라 색상 변경" },
      { label: "default padding", value: "12px", note: "`p-3`" },
      { label: "alert background", value: "linear-gradient(135deg, var(--tb-taste-sweet-bg) 0%, var(--tb-color-surface-base) 100%)" },
      { label: "neutral background", value: "var(--tb-color-surface-card)" },
      { label: "alert border color", value: "var(--tb-taste-sweet-light)" },
      { label: "neutral border color", value: "var(--tb-color-border-card)" },
      { label: "icon size", value: "32px" },
      { label: "icon radius", value: "var(--tb-radius-10)" },
      { label: "title font", value: "13px / 600" },
      { label: "description font", value: "12px / line-height relaxed" },
      { label: "meta font", value: "11px / 500" },
      { label: "action button", value: "PrimaryButton compact" },
    ],
  },
  {
    id: "top-app-bar",
    name: "TopAppBar",
    group: "내비게이션",
    status: "currently-used",
    description: "상단 앱 바와 아이콘 액션 영역입니다.",
    selector: "src/components/TopAppBar.tsx root div",
    sources: [
      { file: "src/components/TopAppBar.tsx", note: "전체 레이아웃과 아이콘 버튼, 아바타가 모두 여기 있습니다." },
    ],
    values: [
      { label: "shell background", value: "var(--tb-color-bg-page) / 85%", note: "`bg-[var(--tb-color-bg-page)]/85`" },
      { label: "backdrop blur", value: "12px", note: "`backdrop-blur-md`" },
      { label: "shell border", value: "1px solid transparent", note: "스크롤 콘텐츠 위에 얇은 분리선 역할" },
      { label: "horizontal padding", value: "20px", note: "`px-[20px]`" },
      { label: "vertical padding", value: "12px", note: "`py-[12px]`" },
      { label: "max height", value: "56px" },
      { label: "avatar size", value: "32px" },
      { label: "avatar border", value: "1px solid var(--tb-color-border-avatar)" },
      { label: "title font", value: "15px / 700" },
      { label: "action gap", value: "16px" },
      { label: "icon size", value: "24px" },
      { label: "icon color", value: "var(--tb-color-icon-primary)" },
      { label: "icon hover color", value: "var(--tb-color-text-primary)" },
      { label: "unread dot", value: "6px circle / var(--tb-taste-sweet-main)", note: "알림 아이콘 우상단 배지" },
    ],
  },
  {
    id: "bottom-tab-bar",
    name: "BottomTabBar",
    group: "내비게이션",
    status: "currently-used",
    description: "하단 탭 바입니다. iOS home indicator는 시스템 기본 표시만 사용합니다.",
    selector: "src/components/BottomTabBar.tsx root div",
    sources: [
      { file: "src/components/BottomTabBar.tsx", note: "tab button, active state 정의" },
    ],
    values: [
      { label: "min-height", value: "60px", note: "`var(--tb-size-bottom-tab-bar-height)`" },
      { label: "background-color", value: "var(--tb-color-bg-page) / 85%", note: "`bg-[var(--tb-color-bg-page)]/85`" },
      { label: "backdrop blur", value: "12px", note: "`backdrop-blur-md`" },
      { label: "border-top", value: "1px solid var(--tb-color-border-default)" },
      { label: "tab padding", value: "6px 16px" },
      { label: "tab gap", value: "2px" },
      { label: "icon size", value: "24px" },
      { label: "label font", value: "10px" },
      { label: "active icon/text color", value: "var(--tb-color-text-primary)" },
      { label: "inactive icon/text color", value: "var(--tb-color-icon-muted)" },
      { label: "hover icon/text color", value: "var(--tb-color-icon-hover)" },
      { label: "active scale", value: "1.1" },
      { label: "press scale", value: "0.92", note: "탭 버튼 active 상태" },
      { label: "active stroke width", value: "2.2" },
    ],
  },
  {
    id: "notification-panel",
    name: "NotificationPanel",
    group: "오버레이",
    status: "currently-used",
    description: "TopAppBar 알림 액션과 연결된 상단 notification overlay입니다.",
    selector: "src/components/NotificationPanel.tsx root overlay",
    sources: [
      { file: "src/components/NotificationPanel.tsx", note: "backdrop, sticky header, notification row가 정의됩니다." },
    ],
    values: [
      { label: "panel width", value: "max-width 1440px / inset-x full" },
      { label: "panel offset", value: "top 56px, horizontal margin 20px" },
      { label: "max height", value: "70vh" },
      { label: "panel radius", value: "var(--tb-radius-20)" },
      { label: "panel background", value: "white / 85%", note: "`bg-white/85` + backdrop blur" },
      { label: "shadow", value: "var(--tb-shadow-drawer)" },
      { label: "header", value: "sticky / bg var(--tb-color-surface-card) / px 20px / pt 20px / pb 12px" },
      { label: "row radius", value: "var(--tb-radius-14)" },
      { label: "row unread state", value: "bg var(--tb-color-surface-muted)" },
      { label: "row read state", value: "opacity 0.6" },
      { label: "icon box", value: "36px / radius var(--tb-radius-10)" },
      { label: "unread dot", value: "6px circle / var(--tb-taste-sweet-main)" },
    ],
  },
  {
    id: "app-menu-drawer",
    name: "AppMenuDrawer",
    group: "오버레이",
    status: "currently-used",
    description: "TopAppBar 메뉴 액션과 연결된 우측 glass drawer입니다.",
    selector: "src/components/AppMenuDrawer.tsx right drawer",
    sources: [
      { file: "src/components/AppMenuDrawer.tsx", note: "backdrop, header, profile summary, section list, footer action이 정의됩니다." },
    ],
    values: [
      { label: "drawer width", value: "300px", note: "`w-[300px] max-w-[85vw]`" },
      { label: "drawer background", value: "white / 85%", note: "`bg-white/85` + backdrop blur" },
      { label: "backdrop", value: "black / 30% + blur 2px" },
      { label: "shadow", value: "var(--tb-shadow-drawer)" },
      { label: "transition", value: "transform 300ms cubic-bezier(0.22,1,0.36,1)" },
      { label: "header padding", value: "20px 20px 16px" },
      { label: "profile card", value: "radius var(--tb-radius-14) / muted surface / padding 12px" },
      { label: "section label", value: "11px / 600 / uppercase" },
      { label: "row radius", value: "var(--tb-radius-12)" },
      { label: "row padding", value: "12px" },
      { label: "footer border", value: "1px solid var(--tb-color-border-default)" },
    ],
  },
  {
    id: "empty-state",
    name: "EmptyState",
    group: "피드백",
    status: "currently-used",
    description: "예약이 비어 있거나 다음 액션이 없을 때 안내하는 공용 empty state입니다.",
    selector: "src/components/system/EmptyState.tsx root div",
    sources: [
      { file: "src/components/system/EmptyState.tsx", note: "아이콘, 타이틀, 설명, 선택 CTA가 모두 정의됩니다." },
      { file: "src/pages/ReservationPage.tsx", note: "예약이 없을 때 실제 사용 예시입니다." },
    ],
    values: [
      { label: "layout", value: "flex column / centered / text-center" },
      { label: "gap", value: "16px", note: "`gap-4`" },
      { label: "padding", value: "48px 24px", note: "`py-12 px-6`" },
      { label: "icon box", value: "48px / radius 14px / muted surface" },
      { label: "title font", value: "16px / 700" },
      { label: "description font", value: "13px / relaxed" },
      { label: "cta radius", value: "10px" },
      { label: "cta padding", value: "10px 20px" },
      { label: "cta background", value: "var(--tb-color-text-primary)" },
      { label: "cta active scale", value: "0.98" },
    ],
  },
  {
    id: "badge",
    name: "Badge",
    group: "배지",
    status: "defined-but-unused",
    description: "공용 shadcn badge 프리미티브입니다.",
    selector: "badgeVariants() in src/components/ui/badge.tsx",
    sources: [
      { file: "src/components/ui/badge.tsx", note: "base + variant class map이 모두 여기에 있습니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "padding", value: "2px 8px", note: "`px-2 py-0.5`" },
      { label: "font-size", value: "12px", note: "`text-xs`" },
      { label: "font-weight", value: "500", note: "`font-medium`" },
      { label: "gap", value: "4px", note: "`gap-1`" },
      { label: "default variant", value: "bg-primary / text-primary-foreground" },
      { label: "secondary variant", value: "bg-secondary / text-secondary-foreground" },
      { label: "outline variant", value: "text-foreground + hover accent" },
      { label: "destructive variant", value: "bg-destructive / text-white" },
    ],
  },
  {
    id: "button",
    name: "Button",
    group: "버튼",
    status: "defined-but-unused",
    description: "공용 shadcn button 프리미티브입니다.",
    selector: "buttonVariants() in src/components/ui/button.tsx",
    sources: [
      { file: "src/components/ui/button.tsx", note: "variant와 size class map이 모두 여기에 있습니다." },
    ],
    values: [
      { label: "display", value: "inline-flex" },
      { label: "gap", value: "8px", note: "`gap-2`" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "font-size", value: "14px", note: "`text-sm`" },
      { label: "font-weight", value: "500", note: "`font-medium`" },
      { label: "focus ring", value: "3px" },
      { label: "default size", value: "height 36px, padding 8px 16px" },
      { label: "sm size", value: "height 32px, padding 8px 12px" },
      { label: "lg size", value: "height 40px, padding 8px 24px" },
      { label: "icon size", value: "36px x 36px" },
      { label: "default variant", value: "bg-primary / text-primary-foreground" },
      { label: "outline variant", value: "border + bg-background + hover accent" },
      { label: "ghost variant", value: "background on hover only" },
    ],
  },
  {
    id: "input",
    name: "Input",
    group: "필드",
    status: "defined-but-unused",
    description: "공용 input 프리미티브입니다.",
    selector: "src/components/ui/input.tsx data-slot=input",
    sources: [
      { file: "src/components/ui/input.tsx" },
    ],
    values: [
      { label: "height", value: "36px", note: "`h-9`" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "border color", value: "token: border-input" },
      { label: "background-color", value: "token: bg-input-background" },
      { label: "padding-inline", value: "12px", note: "`px-3`" },
      { label: "padding-block", value: "4px", note: "`py-1`" },
      { label: "font-size", value: "16px base / md 14px", note: "`text-base md:text-sm`" },
      { label: "placeholder color", value: "token: muted-foreground" },
      { label: "focus ring", value: "3px" },
      { label: "disabled state", value: "pointer-events none + opacity 0.5" },
    ],
  },
  {
    id: "textarea",
    name: "Textarea",
    group: "필드",
    status: "defined-but-unused",
    description: "공용 textarea 프리미티브입니다.",
    selector: "src/components/ui/textarea.tsx data-slot=textarea",
    sources: [
      { file: "src/components/ui/textarea.tsx" },
    ],
    values: [
      { label: "min-height", value: "64px", note: "`min-h-16`" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "border color", value: "token: border-input" },
      { label: "background-color", value: "token: bg-input-background" },
      { label: "padding-inline", value: "12px", note: "`px-3`" },
      { label: "padding-block", value: "8px", note: "`py-2`" },
      { label: "font-size", value: "16px base / md 14px" },
      { label: "focus ring", value: "3px" },
      { label: "resize", value: "none" },
      { label: "disabled state", value: "opacity 0.5" },
    ],
  },
  {
    id: "select-trigger",
    name: "SelectTrigger",
    group: "필드",
    status: "defined-but-unused",
    description: "공용 select 트리거 입력면입니다.",
    selector: "src/components/ui/select.tsx data-slot=select-trigger",
    sources: [
      { file: "src/components/ui/select.tsx", note: "trigger, content, item class map이 여기 있습니다." },
    ],
    values: [
      { label: "height", value: "36px default / 32px sm" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "border color", value: "token: border-input" },
      { label: "background-color", value: "token: bg-input-background" },
      { label: "padding-inline", value: "12px", note: "`px-3`" },
      { label: "padding-block", value: "8px", note: "`py-2`" },
      { label: "font-size", value: "14px", note: "`text-sm`" },
      { label: "gap", value: "8px", note: "`gap-2`" },
      { label: "focus ring", value: "3px" },
      { label: "icon size", value: "16px" },
    ],
  },
  {
    id: "tabs",
    name: "Tabs",
    group: "내비게이션",
    status: "defined-but-unused",
    description: "공용 segmented tabs 프리미티브입니다.",
    selector: "src/components/ui/tabs.tsx data-slot=tabs-*",
    sources: [
      { file: "src/components/ui/tabs.tsx", note: "TabsList, TabsTrigger, TabsContent 정의" },
    ],
    values: [
      { label: "root gap", value: "8px", note: "`gap-2`" },
      { label: "list height", value: "36px", note: "`h-9`" },
      { label: "list radius", value: "12px", note: "`rounded-xl`" },
      { label: "list padding", value: "3px" },
      { label: "trigger radius", value: "12px", note: "`rounded-xl`" },
      { label: "trigger padding", value: "4px 8px", note: "`px-2 py-1`" },
      { label: "trigger font", value: "14px / 500" },
      { label: "active background", value: "bg-card" },
      { label: "focus ring", value: "3px" },
    ],
  },
  {
    id: "dialog-content",
    name: "DialogContent",
    group: "오버레이",
    status: "defined-but-unused",
    description: "공용 dialog 콘텐츠 패널입니다.",
    selector: "src/components/ui/dialog.tsx data-slot=dialog-content",
    sources: [
      { file: "src/components/ui/dialog.tsx", note: "overlay, content, title, description 정의" },
    ],
    values: [
      { label: "position", value: "fixed center" },
      { label: "max-width", value: "calc(100% - 2rem), sm max 32rem" },
      { label: "gap", value: "16px", note: "`gap-4`" },
      { label: "border-radius", value: "8px", note: "`rounded-lg`" },
      { label: "border", value: "1px solid" },
      { label: "padding", value: "24px", note: "`p-6`" },
      { label: "shadow", value: "shadow-lg" },
      { label: "overlay", value: "bg-black/50" },
      { label: "close button position", value: "top 16px / right 16px" },
    ],
  },
  {
    id: "sheet-content",
    name: "SheetContent",
    group: "오버레이",
    status: "defined-but-unused",
    description: "공용 sheet / bottom sheet 콘텐츠 패널입니다.",
    selector: "src/components/ui/sheet.tsx data-slot=sheet-content",
    sources: [
      { file: "src/components/ui/sheet.tsx", note: "side별 레이아웃과 overlay 정의" },
    ],
    values: [
      { label: "position", value: "fixed" },
      { label: "display", value: "flex column" },
      { label: "gap", value: "16px", note: "`gap-4`" },
      { label: "shadow", value: "shadow-lg" },
      { label: "right side size", value: "75% width, sm max-width small" },
      { label: "bottom side size", value: "full width, auto height, border-top" },
      { label: "header padding", value: "16px", note: "`p-4`" },
      { label: "footer padding", value: "16px", note: "`p-4`" },
      { label: "overlay", value: "bg-black/50" },
    ],
  },
  {
    id: "popover-content",
    name: "PopoverContent",
    group: "오버레이",
    status: "defined-but-unused",
    description: "공용 popover 콘텐츠 패널입니다.",
    selector: "src/components/ui/popover.tsx data-slot=popover-content",
    sources: [
      { file: "src/components/ui/popover.tsx" },
    ],
    values: [
      { label: "width", value: "288px", note: "`w-72`" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "border", value: "1px solid" },
      { label: "padding", value: "16px", note: "`p-4`" },
      { label: "background-color", value: "token: bg-popover" },
      { label: "text color", value: "token: text-popover-foreground" },
      { label: "shadow", value: "shadow-md" },
      { label: "side offset", value: "4px default" },
    ],
  },
  {
    id: "tooltip-content",
    name: "TooltipContent",
    group: "오버레이",
    status: "defined-but-unused",
    description: "공용 tooltip 콘텐츠 패널입니다.",
    selector: "src/components/ui/tooltip.tsx data-slot=tooltip-content",
    sources: [
      { file: "src/components/ui/tooltip.tsx" },
    ],
    values: [
      { label: "width", value: "fit-content" },
      { label: "border-radius", value: "6px", note: "`rounded-md`" },
      { label: "padding", value: "6px 12px", note: "`px-3 py-1.5`" },
      { label: "font-size", value: "12px", note: "`text-xs`" },
      { label: "background-color", value: "token: bg-primary" },
      { label: "text color", value: "token: text-primary-foreground" },
      { label: "arrow size", value: "10px", note: "`size-2.5`" },
      { label: "side offset", value: "0px default" },
    ],
  },
];

function formatStatus(status: ComponentStyleSpecStatus) {
  return status === "currently-used" ? "Currently used" : "Defined but unused";
}

export function buildComponentStyleSnippet(spec: ComponentStyleSpec) {
  return [
    `컴포넌트: ${spec.name}`,
    `분류: ${spec.group}`,
    `상태: ${formatStatus(spec.status)}`,
    "",
    "수정 파일:",
    ...spec.sources.map((source) =>
      source.note ? `- ${source.file} (${source.note})` : `- ${source.file}`,
    ),
    ...(spec.selector ? ["", `선택자/루트: ${spec.selector}`] : []),
    "",
    "현재 스타일 값:",
    ...spec.values.map((value) =>
      value.note
        ? `- ${value.label}: ${value.value} (${value.note})`
        : `- ${value.label}: ${value.value}`,
    ),
    ...(spec.note ? ["", "메모:", `- ${spec.note}`] : []),
  ].join("\n");
}

export function buildComponentCodexPrompt(spec: ComponentStyleSpec) {
  return [
    "아래 컴포넌트의 현재 스타일을 기준으로 수정해줘.",
    "",
    `컴포넌트: ${spec.name}`,
    `분류: ${spec.group}`,
    `상태: ${formatStatus(spec.status)}`,
    "",
    "수정 파일:",
    ...spec.sources.map((source) =>
      source.note ? `- ${source.file} (${source.note})` : `- ${source.file}`,
    ),
    ...(spec.selector ? ["", `선택자/루트: ${spec.selector}`] : []),
    "",
    "현재 스타일 값:",
    ...spec.values.map((value) =>
      value.note
        ? `- ${value.label}: ${value.value} (${value.note})`
        : `- ${value.label}: ${value.value}`,
    ),
    ...(spec.note ? ["", "메모:", `- ${spec.note}`] : []),
    "",
    "요청사항:",
    "- [여기에 원하는 변경사항을 적어주세요]",
    "",
    "조건:",
    "- 기존 디자인 언어와 토큰 구조를 최대한 유지해줘.",
    "- 가능하면 var(--tb-*) 토큰을 우선 재사용해줘.",
    "- 관련 상태/variant가 있으면 함께 정리해줘.",
    "- 수정 후 어떤 파일이 바뀌었는지 함께 알려줘.",
  ].join("\n");
}
