export const TASTE_CIRCULAR_LOOP_PULSE_DURATION_MS = 1600;
export const TASTE_CIRCULAR_LOOP_STEP_PULSES = 1;
export const TASTE_CIRCULAR_LOOP_STEP_ADVANCE_MS =
  TASTE_CIRCULAR_LOOP_PULSE_DURATION_MS * TASTE_CIRCULAR_LOOP_STEP_PULSES;
export const TASTE_CIRCULAR_LOOP_NODE_PULSE_SCALE = 1.28;
export const TASTE_CIRCULAR_LOOP_LABEL_PULSE_SCALE = 1.06;
