import { DATA_VIZ_TOKENS, MOTION_TOKENS } from '../../constants/designTokens';

export const TASTE_CIRCULAR_LOOP_PULSE_DURATION_MS = MOTION_TOKENS.durationMs.loopPulse;
export const TASTE_CIRCULAR_LOOP_STEP_PULSES = DATA_VIZ_TOKENS.ring.stepPulses;
export const TASTE_CIRCULAR_LOOP_STEP_ADVANCE_MS =
  TASTE_CIRCULAR_LOOP_PULSE_DURATION_MS * TASTE_CIRCULAR_LOOP_STEP_PULSES;
export const TASTE_CIRCULAR_LOOP_NODE_PULSE_SCALE = MOTION_TOKENS.scale.loopNodePulse;
export const TASTE_CIRCULAR_LOOP_LABEL_PULSE_SCALE = MOTION_TOKENS.scale.loopLabelPulse;
