import type { TasteSurveyItem } from '../types/tasteSurvey';

export const TASTE_SURVEY_ITEMS = [
  {
    id: 'sweet-salience-v1',
    tasteId: 'sweet',
    construct: 'salience',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '잘 익은 바나나 한 입',
      description: '잘 익은 바나나를 한 입 먹었을 때의 단맛을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 단맛의 작은 차이도 비교적 빨리 또렷하게 느껴졌어요.',
  },
  {
    id: 'sweet-overload-v1',
    tasteId: 'sweet',
    construct: 'overload',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '잘 익은 바나나 한 입',
      description: '같은 바나나라도 더 달게 느껴지는 한 입을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 단맛이 조금만 강해져도 쉽게 과하게 느껴졌어요.',
  },
  {
    id: 'salty-salience-v1',
    tasteId: 'salty',
    construct: 'salience',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '맑은 물에 소금을 한 꼬집 더한 맛',
      description: '맑은 물이나 아주 연한 국물에 소금 한 꼬집이 더해진 짠맛을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 짠맛의 작은 차이도 비교적 빨리 또렷하게 느껴졌어요.',
  },
  {
    id: 'salty-overload-v1',
    tasteId: 'salty',
    construct: 'overload',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '맑은 물에 소금을 한 꼬집 더한 맛',
      description: '소금기가 한 단계 더해졌을 때 입안에서 느껴지는 짠맛을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 짠맛이 조금만 강해져도 쉽게 부담스럽게 느껴졌어요.',
  },
  {
    id: 'sour-salience-v1',
    tasteId: 'sour',
    construct: 'salience',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '레몬즙이 살짝 들어간 물 한 모금',
      description: '물 한 모금에 레몬즙이 조금 들어갔을 때의 신맛을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 신맛의 작은 차이도 비교적 빨리 또렷하게 느껴졌어요.',
  },
  {
    id: 'sour-overload-v1',
    tasteId: 'sour',
    construct: 'overload',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '레몬즙이 살짝 들어간 물 한 모금',
      description: '레몬즙이 조금 더 들어갔을 때 입안에서 올라오는 신맛을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 신맛이 조금만 강해져도 쉽게 과하게 느껴졌어요.',
  },
  {
    id: 'bitter-salience-v1',
    tasteId: 'bitter',
    construct: 'salience',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '아메리카노 첫 모금',
      description: '아메리카노를 처음 마셨을 때 입안에 바로 닿는 쓴맛을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 쓴맛의 작은 차이도 비교적 빨리 또렷하게 느껴졌어요.',
  },
  {
    id: 'bitter-overload-v1',
    tasteId: 'bitter',
    construct: 'overload',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '아메리카노 첫 모금',
      description: '아메리카노의 쓴맛이 한 단계 더 강하게 느껴지는 상황을 떠올리는 기준입니다.',
      stability: 'medium',
    },
    prompt: '최근 3개월 동안 쓴맛이 조금만 강해져도 쉽게 부담스럽게 느껴졌어요.',
  },
  {
    id: 'umami-salience-v1',
    tasteId: 'umami',
    construct: 'salience',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '맑은 버섯 육수 한 숟갈',
      description: '간을 세게 하지 않은 맑은 버섯 육수에서 느껴지는 감칠맛을 떠올리는 기준입니다.',
      stability: 'low',
    },
    exploratoryMetadata: {
      appliesToTasteIds: ['umami'],
      rationale: '감칠맛은 재료 상태와 농도, 짠맛의 영향이 함께 작용할 수 있어 v1에서는 탐색 축으로 다룹니다.',
      interpretationCaution: '단일 응답만으로 확정하지 않고 반복 응답과 식후 피드백을 함께 보며 해석해야 합니다.',
    },
    prompt: '최근 3개월 동안 감칠맛의 작은 차이도 비교적 빨리 또렷하게 느껴졌어요.',
  },
  {
    id: 'umami-overload-v1',
    tasteId: 'umami',
    construct: 'overload',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '맑은 버섯 육수 한 숟갈',
      description: '버섯 육수의 감칠맛이 한 단계 더 진해졌을 때를 떠올리는 기준입니다.',
      stability: 'low',
    },
    exploratoryMetadata: {
      appliesToTasteIds: ['umami'],
      rationale: '감칠맛의 과함은 짠맛이나 농도와 겹쳐 느껴질 수 있어 v1에서는 탐색적으로 기록합니다.',
      interpretationCaution: '셰프 가이드에서는 감칠맛을 줄이라는 지시가 아니라 강도와 누적감을 조절할 참고 신호로 사용해야 합니다.',
    },
    prompt: '최근 3개월 동안 감칠맛이 조금만 강해져도 쉽게 무겁거나 과하게 느껴졌어요.',
  },
  {
    id: 'fat-salience-v1',
    tasteId: 'fat',
    construct: 'salience',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '무가당 생크림의 지방감',
      description: '단맛을 더하지 않은 생크림 한 숟갈에서 느껴지는 지방감을 떠올리는 기준입니다.',
      stability: 'low',
    },
    exploratoryMetadata: {
      appliesToTasteIds: ['fat'],
      rationale: '지방감은 질감, 온도, 양의 영향을 크게 받을 수 있어 v1에서는 탐색 축으로 다룹니다.',
      interpretationCaution: '기호 판단이 아니라 지방감의 인지 속도와 부담 신호를 중심으로 해석해야 합니다.',
    },
    prompt: '최근 3개월 동안 지방감의 작은 차이도 비교적 빨리 또렷하게 느껴졌어요.',
  },
  {
    id: 'fat-overload-v1',
    tasteId: 'fat',
    construct: 'overload',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      label: '무가당 생크림의 지방감',
      description: '생크림의 지방감이 한 단계 더 두껍게 느껴지는 상황을 떠올리는 기준입니다.',
      stability: 'low',
    },
    exploratoryMetadata: {
      appliesToTasteIds: ['fat'],
      rationale: '지방감의 과함은 질감과 잔여감에 따라 달라질 수 있어 v1에서는 탐색적으로 기록합니다.',
      interpretationCaution: '셰프 가이드에서는 지방을 배제하라는 뜻이 아니라 잔여감과 정리감을 조절할 참고 신호로 사용해야 합니다.',
    },
    prompt: '최근 3개월 동안 지방감이 조금만 강해져도 쉽게 부담스럽게 느껴졌어요.',
  },
] as const satisfies readonly TasteSurveyItem[];
