import type {
  DishSignalWeights,
  FeedbackTagDefinition,
  ResearchRule,
} from '../types/tastePersonalization';

export const DEFAULT_DISH_SIGNAL_WEIGHTS: DishSignalWeights = {
  ingredient: 0.45,
  technique: 0.2,
  menu: 0.1,
  review: 0.15,
  course: 0.1,
};

// Seed rules for the MVP. Treat them as evidence-backed heuristics to calibrate over time,
// not immutable truth.
export const DEFAULT_RESEARCH_RULES: readonly ResearchRule[] = [
  {
    ruleCode: 'sweet_suppresses_bitterness',
    label: '단맛은 쓴맛을 누를 수 있음',
    summary:
      '당도는 쓴맛 지각을 완화하는 경향이 있어, 디저트나 소스에서 bitterness 인상이 과소평가될 수 있습니다.',
    evidenceStrength: 0.72,
    triggerTasteFloor: { sweet: 0.4 },
    effectTasteDelta: { bitter: -0.18 },
    notes: ['taste-taste interaction review 기반 seed rule'],
  },
  {
    ruleCode: 'sodium_reduces_bitterness',
    label: '짠맛은 쓴맛을 누를 수 있음',
    summary:
      '적절한 나트륨은 bitterness를 줄여줄 수 있지만, salt가 과하면 오히려 dish balance를 흐릴 수 있습니다.',
    evidenceStrength: 0.66,
    triggerTasteFloor: { salty: 0.3 },
    effectTasteDelta: { bitter: -0.12 },
  },
  {
    ruleCode: 'umami_synergy',
    label: '감칠맛 상승효과',
    summary:
      '글루탐산과 뉴클레오타이드 조합은 umami 인상을 더 크게 만들 수 있어, stock/jus/fermentation 기반 dish에서 상승효과를 고려합니다.',
    evidenceStrength: 0.83,
    triggerTasteFloor: { umami: 0.45 },
    effectTasteDelta: { umami: 0.15, salty: 0.04 },
  },
  {
    ruleCode: 'fat_needs_relief',
    label: '지방감은 산미나 정리감이 필요함',
    summary:
      'fat intensity가 높은 dish는 acidity, herbs, temperature contrast가 없으면 heaviness와 linger가 빠르게 올라갈 수 있습니다.',
    evidenceStrength: 0.77,
    triggerTasteFloor: { fat: 0.55 },
    effectPerceptualDelta: { heaviness: 0.18, linger: 0.14, cleanFinish: -0.12 },
  },
  {
    ruleCode: 'smoke_can_mask_detail',
    label: '훈연향은 섬세한 재료 분리를 가릴 수 있음',
    summary:
      'smoke/aroma intensity가 높으면 bitterness와 aroma dominance가 올라가고, delicate notes 분리가 떨어질 수 있습니다.',
    evidenceStrength: 0.7,
    triggerPerceptualFloor: { smoke: 0.45, aromaIntensity: 0.45 },
    effectPerceptualDelta: { smoke: 0.18, aromaIntensity: 0.1, cleanFinish: -0.08 },
    effectTasteDelta: { bitter: 0.08 },
  },
  {
    ruleCode: 'temperature_modulates_taste',
    label: '온도는 taste adaptation을 바꿈',
    summary:
      'temperature는 sweetness adaptation, overall salience, tactile impression을 바꿔 perceived intensity를 흔들 수 있습니다.',
    evidenceStrength: 0.64,
    triggerPerceptualFloor: { thermalImpact: 0.35 },
    effectPerceptualDelta: { thermalImpact: 0.12, brightness: 0.06 },
  },
];

export const DEFAULT_FEEDBACK_TAG_DEFINITIONS: readonly FeedbackTagDefinition[] = [
  {
    id: 'acid-too-sharp',
    label: '산미가 조금 날카로웠어요',
    summary: '산미가 전면으로 치고 올라오며 다른 인상을 눌렀다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { sour: 0.72, umami: -0.14 },
    perceptionPerceptualDelta: { brightness: 0.34, linger: 0.08, cleanFinish: -0.06 },
    preferenceTasteDelta: { sour: -0.52 },
    preferencePerceptualDelta: { brightness: -0.12, cleanFinish: -0.08 },
    confidence: 0.86,
  },
  {
    id: 'oyster-aroma-forward',
    label: '굴 향이 먼저 치고 올라왔어요',
    summary: 'aroma dominance와 iodine/briny note가 입구감을 주도했다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { salty: 0.22, umami: 0.24 },
    perceptionPerceptualDelta: { aromaIntensity: 0.64, heaviness: 0.24, brightness: -0.1 },
    preferenceTasteDelta: { salty: -0.1 },
    preferencePerceptualDelta: { aromaIntensity: -0.38 },
    confidence: 0.74,
  },
  {
    id: 'starter-balanced',
    label: '첫 코스로 가장 좋았어요',
    summary: '산미와 clean finish가 코스 도입부에서 잘 작동했다는 신호입니다.',
    polarity: 'positive',
    perceptionTasteDelta: { sour: 0.12 },
    perceptionPerceptualDelta: { brightness: 0.18, cleanFinish: 0.32 },
    preferenceTasteDelta: { sour: 0.34 },
    preferencePerceptualDelta: { brightness: 0.2, cleanFinish: 0.42 },
    confidence: 0.7,
  },
  {
    id: 'butter-too-long',
    label: '버터감이 길게 남았어요',
    summary: 'fat intensity와 linger가 길어 clean finish가 부족했다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { fat: 0.74, salty: 0.16, umami: 0.08 },
    perceptionPerceptualDelta: { heaviness: 0.78, linger: 0.88, cleanFinish: -0.68 },
    preferenceTasteDelta: { fat: -0.58 },
    preferencePerceptualDelta: { heaviness: -0.42, linger: -0.48, cleanFinish: 0.22 },
    confidence: 0.91,
  },
  {
    id: 'finish-too-short',
    label: '피니시가 생각보다 짧았어요',
    summary: '감칠맛/향의 tail이 기대보다 빨리 끊겼다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { umami: -0.46 },
    perceptionPerceptualDelta: { linger: -0.36, cleanFinish: 0.08 },
    preferenceTasteDelta: { umami: 0.36 },
    preferencePerceptualDelta: { linger: 0.24 },
    confidence: 0.78,
  },
  {
    id: 'fish-balanced',
    label: '지금 밸런스가 딱 좋았어요',
    summary: 'fat, umami, freshness 간 균형이 안정적이었다는 신호입니다.',
    polarity: 'positive',
    perceptionTasteDelta: { umami: 0.1, fat: 0.08 },
    perceptionPerceptualDelta: { cleanFinish: 0.2, linger: 0.1 },
    preferenceTasteDelta: { umami: 0.24, fat: 0.1 },
    preferencePerceptualDelta: { cleanFinish: 0.24 },
    confidence: 0.68,
  },
  {
    id: 'umami-flat',
    label: '감칠맛이 기대보다 짧았어요',
    summary: '메인의 중심 감칠맛이 기대보다 덜 길게 느껴졌다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { umami: -0.54 },
    perceptionPerceptualDelta: { linger: -0.18, aromaIntensity: -0.08 },
    preferenceTasteDelta: { umami: 0.42 },
    preferencePerceptualDelta: { linger: 0.14 },
    confidence: 0.82,
  },
  {
    id: 'smoke-over',
    label: '훈연향이 재료를 덮었어요',
    summary: 'smoke와 aroma dominance가 지나쳐 ingredient separation이 떨어졌다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { bitter: 0.18 },
    perceptionPerceptualDelta: { smoke: 0.84, aromaIntensity: 0.32, cleanFinish: -0.12 },
    preferenceTasteDelta: { bitter: -0.18 },
    preferencePerceptualDelta: { smoke: -0.62, aromaIntensity: -0.24 },
    confidence: 0.88,
  },
  {
    id: 'main-balanced',
    label: '메인으로 가장 만족스러웠어요',
    summary: '육향, 감칠맛, 직화 향의 볼륨이 사용자의 취향과 잘 맞았다는 신호입니다.',
    polarity: 'positive',
    perceptionTasteDelta: { umami: 0.12, fat: 0.06 },
    perceptionPerceptualDelta: { aromaIntensity: 0.14, linger: 0.16 },
    preferenceTasteDelta: { umami: 0.46, fat: 0.14 },
    preferencePerceptualDelta: { aromaIntensity: 0.18, linger: 0.12 },
    confidence: 0.76,
  },
  {
    id: 'sweet-front',
    label: '단맛이 먼저 치고 올라왔어요',
    summary: 'dessert finish에서 sweetness salience가 과도했다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { sweet: 0.72, fat: 0.18 },
    perceptionPerceptualDelta: { linger: 0.34, brightness: -0.16, cleanFinish: -0.12 },
    preferenceTasteDelta: { sweet: -0.52 },
    preferencePerceptualDelta: { cleanFinish: 0.12 },
    confidence: 0.87,
  },
  {
    id: 'acid-missing',
    label: '고소함은 좋지만 산미가 부족했어요',
    summary: '후반 무게감을 정리할 acidity/brightness가 부족했다는 신호입니다.',
    polarity: 'mixed',
    perceptionTasteDelta: { sour: -0.58, fat: 0.16 },
    perceptionPerceptualDelta: { brightness: -0.22, heaviness: 0.32, cleanFinish: -0.28 },
    preferenceTasteDelta: { sour: 0.54 },
    preferencePerceptualDelta: { brightness: 0.28, cleanFinish: 0.34 },
    confidence: 0.9,
  },
  {
    id: 'dessert-balanced',
    label: '식사의 끝맛과 잘 이어졌어요',
    summary: 'dessert의 sweetness, grain aroma, moisture balance가 안정적이었다는 신호입니다.',
    polarity: 'positive',
    perceptionTasteDelta: { sweet: 0.08, fat: 0.06 },
    perceptionPerceptualDelta: { cleanFinish: 0.26, linger: 0.1 },
    preferenceTasteDelta: { sweet: 0.18, fat: 0.08 },
    preferencePerceptualDelta: { cleanFinish: 0.24 },
    confidence: 0.67,
  },
  {
    id: 'dish-balanced-generic',
    label: '지금 밸런스가 잘 맞았어요',
    summary: '현재 dish의 중심 풍미와 마무리 흐름이 전반적으로 편안하게 받아들여졌다는 신호입니다.',
    polarity: 'positive',
    perceptionTasteDelta: { umami: 0.08, fat: 0.04 },
    perceptionPerceptualDelta: { cleanFinish: 0.2, linger: 0.08 },
    preferenceTasteDelta: { umami: 0.18, fat: 0.08 },
    preferencePerceptualDelta: { cleanFinish: 0.22, linger: 0.1 },
    confidence: 0.64,
  },
  {
    id: 'flavor-too-strong-generic',
    label: '풍미가 조금 강하게 느껴졌어요',
    summary: '풍미의 밀도나 향 존재감이 현재 컨디션 기준으로 다소 강하게 전달됐다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { salty: 0.14, umami: 0.18, fat: 0.14 },
    perceptionPerceptualDelta: { aromaIntensity: 0.24, heaviness: 0.22, cleanFinish: -0.08 },
    preferenceTasteDelta: { salty: -0.08, fat: -0.12 },
    preferencePerceptualDelta: { aromaIntensity: -0.18, heaviness: -0.18 },
    confidence: 0.71,
  },
  {
    id: 'finish-too-heavy-generic',
    label: '끝맛이 조금 무겁게 남았어요',
    summary: 'dish의 마무리에서 heaviness와 linger가 높게 남았다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { fat: 0.42, umami: 0.12 },
    perceptionPerceptualDelta: { heaviness: 0.52, linger: 0.46, cleanFinish: -0.34 },
    preferenceTasteDelta: { fat: -0.3 },
    preferencePerceptualDelta: { heaviness: -0.28, linger: -0.24, cleanFinish: 0.18 },
    confidence: 0.79,
  },
  {
    id: 'finish-too-short-generic',
    label: '인상이 조금 짧게 끝났어요',
    summary: '풍미의 tail이나 여운이 기대보다 짧게 끝났다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { umami: -0.28 },
    perceptionPerceptualDelta: { linger: -0.3, cleanFinish: 0.06 },
    preferenceTasteDelta: { umami: 0.24 },
    preferencePerceptualDelta: { linger: 0.18 },
    confidence: 0.7,
  },
  {
    id: 'sweet-too-forward-generic',
    label: '단맛이 먼저 느껴졌어요',
    summary: '후반 인상에서 sweetness salience가 예상보다 앞에 섰다는 신호입니다.',
    polarity: 'negative',
    perceptionTasteDelta: { sweet: 0.48, fat: 0.12 },
    perceptionPerceptualDelta: { linger: 0.2, brightness: -0.1, cleanFinish: -0.08 },
    preferenceTasteDelta: { sweet: -0.3 },
    preferencePerceptualDelta: { cleanFinish: 0.1 },
    confidence: 0.76,
  },
  {
    id: 'freshness-needed-generic',
    label: '정리감이 조금 더 있으면 좋겠어요',
    summary: '마무리를 정리해줄 acidity나 brightness가 더 있으면 좋겠다는 신호입니다.',
    polarity: 'mixed',
    perceptionTasteDelta: { sour: -0.18, fat: 0.08 },
    perceptionPerceptualDelta: { brightness: -0.18, cleanFinish: -0.24, heaviness: 0.16 },
    preferenceTasteDelta: { sour: 0.24 },
    preferencePerceptualDelta: { brightness: 0.2, cleanFinish: 0.28 },
    confidence: 0.74,
  },
];
