import type { TasteSurveyItem } from '../types/tasteSurvey';

const INTENSITY_HELPER = '최근 3개월의 경험에서 느낀 강도를 골라주세요. 좋아하는 정도나 알맞은 정도는 묻지 않아요.';

export const TASTE_SURVEY_ITEMS: readonly TasteSurveyItem[] = [
  {
    id: 'sweet-recalled-intensity-v2',
    tasteId: 'sweet',
    construct: 'recalled_intensity',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      id: 'binggrae-banana-milk-original-240ml',
      version: '1',
      label: '빙그레 바나나맛우유',
      description: '일반 제품 240mL를 냉장고에서 꺼내, 아무것도 섞지 않고 한 모금 마셨을 때를 떠올려주세요.',
      conditions: ['일반 제품 240mL', '냉장 상태', '첨가·희석 없음', '첫 모금'],
      stability: 'medium',
    },
    prompt: '바나나맛우유의 단맛이 얼마나 강하게 느껴지나요?',
    helper: INTENSITY_HELPER,
  },
  {
    id: 'salty-recalled-intensity-v2',
    tasteId: 'salty',
    construct: 'recalled_intensity',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      id: 'nongshim-shin-ramyun-bag-120g-broth',
      version: '1',
      label: '신라면 국물',
      description: '봉지 신라면 120g을 물 550mL와 스프 전량으로 4분 30초 끓인 국물입니다. 추가 재료 없이 먹었던 경험을 떠올려주세요.',
      conditions: ['봉지 제품 120g', '물 550mL', '스프 전량', '4분 30초 조리', '추가 재료 없음', '국물'],
      stability: 'medium',
    },
    prompt: '이렇게 끓인 신라면 국물의 짠맛이 얼마나 강하게 느껴지나요?',
    helper: '매운 느낌과 구분해 짠맛의 강도를 골라주세요. 안내한 조건의 맛이 기억나지 않으면 따로 표시해 주세요.',
  },
  {
    id: 'sour-recalled-intensity-v2',
    tasteId: 'sour',
    construct: 'recalled_intensity',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      id: 'fresh-orange-flesh',
      version: '1',
      label: '오렌지 과육',
      description: '껍질을 벗긴 생오렌지 과육을 설탕이나 다른 재료 없이 먹었을 때를 떠올려주세요.',
      conditions: ['생과육', '껍질 제외', '첨가 없음', '품종·숙도 미확인'],
      stability: 'low',
    },
    prompt: '오렌지 과육의 신맛이 보통 얼마나 강하게 느껴지나요?',
    helper: INTENSITY_HELPER,
  },
  {
    id: 'bitter-recalled-intensity-v2',
    tasteId: 'bitter',
    construct: 'recalled_intensity',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      id: 'starbucks-hot-americano-tall-original',
      version: '1',
      label: '스타벅스 따뜻한 아메리카노',
      description: 'Tall 355mL, 기본 원두와 기본 샷의 아메리카노입니다. 시럽·설탕·우유·추가 샷 없이 마셨을 때를 떠올려주세요.',
      conditions: ['Tall 355mL', '따뜻한 음료', '기본 원두·기본 샷', '첨가·추가 샷 없음'],
      stability: 'medium',
    },
    prompt: '아메리카노의 쓴맛이 얼마나 강하게 느껴지나요?',
    helper: INTENSITY_HELPER,
  },
  {
    id: 'umami-recalled-intensity-v2',
    tasteId: 'umami',
    construct: 'recalled_intensity',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      id: 'nongshim-saengsaeng-udon-bowl-276g-broth',
      version: '1',
      label: '생생우동 국물',
      description: '생생우동 용기면 276g을 포장지 안내대로 조리한 국물입니다. 추가 양념 없이 한 모금 먹었을 때를 떠올려주세요.',
      conditions: ['용기면 276g', '포장지 조리법·물 표시선 준수', '스프 전량', '추가 양념 없음', '국물'],
      stability: 'medium',
    },
    exploratoryMetadata: {
      appliesToTasteIds: ['umami'],
      rationale: '국물의 감칠맛에는 짠맛과 향이 함께 작용할 수 있어 탐색적으로 기록합니다.',
      interpretationCaution: '짠맛·향·호감과 구분한 회상 응답이며 감칠맛 민감도나 선호로 확정하지 않습니다.',
    },
    prompt: '생생우동 국물의 감칠맛이 얼마나 강하게 느껴지나요?',
    helper: '짠맛이나 향과 구분해, 국물에서 느꼈던 감칠맛의 강도를 골라주세요.',
  },
  {
    id: 'fat-recalled-intensity-v2',
    tasteId: 'fat',
    construct: 'recalled_intensity',
    recallWindow: 'recent-3-months',
    reverseKeyed: false,
    anchor: {
      id: 'seoulmilk-na100-whole-200ml',
      version: '1',
      label: '서울우유 나100% 흰 우유',
      description: '일반 흰 우유 200mL를 냉장고에서 꺼내, 아무것도 섞지 않고 한 모금 마셨을 때를 떠올려주세요.',
      conditions: ['일반 지방 제품 200mL', '냉장 상태', '첨가·희석 없음', '첫 모금'],
      stability: 'medium',
    },
    exploratoryMetadata: {
      appliesToTasteIds: ['fat'],
      rationale: '지방맛은 특정 수용체 하나로 한정하지 않는 지방산 유래 미각을 뜻합니다. 흰 우유는 예비 기준 음식이며 이를 통한 지방맛 측정 타당성은 확인되지 않았습니다.',
      interpretationCaution: '부드러운 질감·입안의 기름막·고소한 향·느끼한 부담을 지방맛으로 치환하지 않습니다. 회상 응답만으로 수용체 반응이나 지방산 민감도를 추정하지 않습니다.',
    },
    prompt: '흰 우유에서 지방맛이 얼마나 강하게 느껴지나요?',
    helper: '지방에서 비롯되는 맛을 떠올려주세요. 부드러운 질감, 고소한 향, 느끼함과 구분하기 어렵다면 아래에 표시해 주세요.',
  },
];
