import type { TbaCoreTasteLexiconEntry } from '../types/tasteBuddyKnowledge';

type LexiconSeed = Omit<
  TbaCoreTasteLexiconEntry,
  'initialConfidence' | 'minRecommendationConfidence' | 'sourceNotes' | 'status' | 'surfaces' | 'version'
> & Partial<
  Pick<
    TbaCoreTasteLexiconEntry,
    'initialConfidence' | 'minRecommendationConfidence' | 'sourceNotes' | 'status' | 'surfaces' | 'version'
  >
>;

const defaultSurfaces: TbaCoreTasteLexiconEntry['surfaces'] = [
  'taste-bubble',
  'detail-tag',
  'dining-note',
];

const core = (entry: LexiconSeed): TbaCoreTasteLexiconEntry => ({
  initialConfidence: 0.42,
  minRecommendationConfidence: 0.72,
  sourceNotes: ['manual-core-lexicon'],
  status: 'candidate',
  surfaces: defaultSurfaces,
  version: '0.1',
  ...entry,
});

export const TBA_CORE_TASTE_LEXICON = [
  core({
    id: 'bright-acidity',
    label: '산뜻한 산미',
    aliases: ['밝은 산미', '상큼함', 'fresh acidity'],
    category: 'taste',
    summary: '입안을 밝게 열고 뒤맛을 가볍게 정리하는 산미 신호입니다.',
    tasteVector: { sour: 0.72, bitter: 0.12, fat: -0.14 },
    perceptualVector: { brightness: 0.76, cleanFinish: 0.58, aromaIntensity: 0.24 },
    dishKindAffinity: { seafood: 0.7, vegetable: 0.56, dessert: 0.48 },
    polarity: 'positive',
  }),
  core({
    id: 'sharp-acidity',
    label: '날카로운 산미',
    aliases: ['찌르는 산미', '강한 산미', 'sharp acidity'],
    category: 'taste',
    summary: '첫 입에서 빠르게 치고 올라와 구조감을 만들지만 피로감을 줄 수 있는 산미입니다.',
    tasteVector: { sour: 0.86, bitter: 0.1, sweet: -0.08 },
    perceptualVector: { brightness: 0.7, thermalImpact: 0.28, cleanFinish: 0.18 },
    dishKindAffinity: { dessert: 0.46, fruit: 0.62, pickled: 0.7 },
    polarity: 'mixed',
  }),
  core({
    id: 'mellow-sweetness',
    label: '둥근 단맛',
    aliases: ['부드러운 단맛', 'round sweetness', '은은한 단맛'],
    category: 'taste',
    summary: '모서리 없이 배경을 받쳐주는 안정적인 단맛입니다.',
    tasteVector: { sweet: 0.62, fat: 0.12, sour: -0.08 },
    perceptualVector: { textureRichness: 0.26, cleanFinish: 0.18, heaviness: 0.12 },
    dishKindAffinity: { dessert: 0.72, vegetable: 0.44, sauce: 0.52 },
    polarity: 'positive',
  }),
  core({
    id: 'clean-sweetness',
    label: '깔끔한 단맛',
    aliases: ['맑은 단맛', 'clean sweetness'],
    category: 'taste',
    summary: '단맛이 남더라도 무겁게 달라붙지 않고 정돈되는 신호입니다.',
    tasteVector: { sweet: 0.58, sour: 0.16, fat: -0.12 },
    perceptualVector: { cleanFinish: 0.58, brightness: 0.34, textureRichness: -0.06 },
    dishKindAffinity: { dessert: 0.74, fruit: 0.66, beverage: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'caramel-sweetness',
    label: '캐러멜 단맛',
    aliases: ['구운 설탕', 'caramelized sweetness'],
    category: 'taste',
    summary: '열을 받은 당이 만드는 깊고 고소한 단맛입니다.',
    tasteVector: { sweet: 0.68, bitter: 0.16, fat: 0.2 },
    perceptualVector: { aromaIntensity: 0.44, textureRichness: 0.34, linger: 0.24 },
    dishKindAffinity: { dessert: 0.82, roasted: 0.64, sauce: 0.52 },
    polarity: 'positive',
  }),
  core({
    id: 'deep-umami',
    label: '깊은 감칠맛',
    aliases: ['진한 감칠맛', 'deep umami'],
    category: 'taste',
    summary: '중반 이후 맛의 바닥을 길게 받쳐주는 감칠맛입니다.',
    tasteVector: { umami: 0.82, salty: 0.18, fat: 0.18 },
    perceptualVector: { linger: 0.7, heaviness: 0.36, textureRichness: 0.18 },
    dishKindAffinity: { broth: 0.76, meat: 0.68, mushroom: 0.72 },
    polarity: 'positive',
  }),
  core({
    id: 'clear-umami',
    label: '맑은 감칠맛',
    aliases: ['투명한 감칠맛', 'clear umami'],
    category: 'taste',
    summary: '무겁지 않게 재료의 깊이를 보여주는 감칠맛입니다.',
    tasteVector: { umami: 0.64, salty: 0.12, fat: -0.12 },
    perceptualVector: { cleanFinish: 0.46, linger: 0.42, brightness: 0.2 },
    dishKindAffinity: { seafood: 0.76, broth: 0.72, vegetable: 0.48 },
    polarity: 'positive',
  }),
  core({
    id: 'fermented-umami',
    label: '발효 감칠맛',
    aliases: ['장맛', 'fermented umami'],
    category: 'taste',
    summary: '발효에서 오는 산미, 짠맛, 감칠맛이 함께 깊이를 만드는 신호입니다.',
    tasteVector: { umami: 0.76, salty: 0.28, sour: 0.22 },
    perceptualVector: { aromaIntensity: 0.58, linger: 0.52, heaviness: 0.24 },
    dishKindAffinity: { fermented: 0.86, sauce: 0.68, meat: 0.48 },
    polarity: 'positive',
  }),
  core({
    id: 'mineral-salinity',
    label: '미네랄 짠맛',
    aliases: ['해수감', 'mineral salinity'],
    category: 'taste',
    summary: '소금기보다 재료의 바다감이나 광물감으로 읽히는 짠맛입니다.',
    tasteVector: { salty: 0.58, umami: 0.3, sour: 0.08 },
    perceptualVector: { brightness: 0.22, cleanFinish: 0.28, aromaIntensity: 0.24 },
    dishKindAffinity: { seafood: 0.86, shellfish: 0.72, broth: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'rounded-salinity',
    label: '둥근 간',
    aliases: ['간이 잘 맞음', 'rounded seasoning'],
    category: 'taste',
    summary: '짠맛이 튀지 않고 전체 맛을 모아주는 균형 신호입니다.',
    tasteVector: { salty: 0.46, umami: 0.24, sweet: 0.08 },
    perceptualVector: { cleanFinish: 0.24, linger: 0.22, heaviness: 0.12 },
    dishKindAffinity: { sauce: 0.7, broth: 0.64, meat: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'clean-bitterness',
    label: '깨끗한 쓴맛',
    aliases: ['정돈된 쓴맛', 'clean bitterness'],
    category: 'taste',
    summary: '맛의 끝을 말끔하게 잡아주는 쓴맛입니다.',
    tasteVector: { bitter: 0.58, sour: 0.12, fat: -0.08 },
    perceptualVector: { cleanFinish: 0.52, brightness: 0.26, linger: 0.22 },
    dishKindAffinity: { vegetable: 0.64, tea: 0.58, chocolate: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'astringent-bitterness',
    label: '떫은 쓴맛',
    aliases: ['수렴감', 'astringent bitterness'],
    category: 'taste',
    summary: '입안을 조이거나 건조하게 만드는 쓴맛과 떫은감입니다.',
    tasteVector: { bitter: 0.78, sour: 0.16, sweet: -0.1 },
    perceptualVector: { thermalImpact: 0.26, cleanFinish: -0.08, textureRichness: -0.16 },
    dishKindAffinity: { tea: 0.7, wine: 0.66, vegetable: 0.42 },
    polarity: 'mixed',
  }),
  core({
    id: 'fatty-richness',
    label: '부드러운 지방감',
    aliases: ['고소한 지방감', 'soft fat richness'],
    category: 'taste',
    summary: '맛을 둥글게 감싸며 포만감과 깊이를 만드는 지방 신호입니다.',
    tasteVector: { fat: 0.72, umami: 0.24, sweet: 0.06 },
    perceptualVector: { textureRichness: 0.68, heaviness: 0.44, linger: 0.28 },
    dishKindAffinity: { meat: 0.78, dairy: 0.68, dessert: 0.54 },
    polarity: 'positive',
  }),
  core({
    id: 'oily-heaviness',
    label: '기름진 무게감',
    aliases: ['오일리함', 'oily heaviness'],
    category: 'taste',
    summary: '지방감이 입안에 오래 남아 무겁게 쌓이는 신호입니다.',
    tasteVector: { fat: 0.84, umami: 0.12, sour: -0.08 },
    perceptualVector: { heaviness: 0.72, textureRichness: 0.54, cleanFinish: -0.34 },
    dishKindAffinity: { fried: 0.76, meat: 0.64, sauce: 0.46 },
    polarity: 'mixed',
  }),
  core({
    id: 'savory-depth',
    label: '구수한 깊이',
    aliases: ['구수함', 'savory depth'],
    category: 'taste',
    summary: '곡물, 장, 구운 향에서 느껴지는 편안한 깊이입니다.',
    tasteVector: { umami: 0.58, bitter: 0.16, fat: 0.12 },
    perceptualVector: { linger: 0.44, aromaIntensity: 0.36, heaviness: 0.18 },
    dishKindAffinity: { grain: 0.72, fermented: 0.62, roasted: 0.54 },
    polarity: 'positive',
  }),
  core({
    id: 'green-freshness',
    label: '풋풋한 신선감',
    aliases: ['초록 향', 'green freshness'],
    category: 'taste',
    summary: '잎채소나 허브에서 오는 가볍고 생생한 신선감입니다.',
    tasteVector: { bitter: 0.24, sour: 0.28, sweet: -0.04 },
    perceptualVector: { brightness: 0.56, aromaIntensity: 0.44, cleanFinish: 0.4 },
    dishKindAffinity: { vegetable: 0.82, herb: 0.76, salad: 0.66 },
    polarity: 'positive',
  }),
  core({
    id: 'lactic-tang',
    label: '유산 발효 산미',
    aliases: ['요거트 산미', 'lactic tang'],
    category: 'taste',
    summary: '유제품이나 발효에서 오는 둥근 산미입니다.',
    tasteVector: { sour: 0.62, fat: 0.16, sweet: 0.08 },
    perceptualVector: { brightness: 0.42, textureRichness: 0.24, cleanFinish: 0.2 },
    dishKindAffinity: { dairy: 0.76, fermented: 0.66, dessert: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'briny-sea',
    label: '해수 감칠맛',
    aliases: ['바다 감칠맛', 'briny sea'],
    category: 'taste',
    summary: '해산물에서 오는 짭조름한 감칠 흐름입니다.',
    tasteVector: { umami: 0.62, salty: 0.46, sour: 0.08 },
    perceptualVector: { aromaIntensity: 0.36, cleanFinish: 0.24, linger: 0.3 },
    dishKindAffinity: { seafood: 0.9, shellfish: 0.78, seaweed: 0.68 },
    polarity: 'positive',
  }),
  core({
    id: 'nutty-sweetness',
    label: '견과 단맛',
    aliases: ['고소한 단맛', 'nutty sweetness'],
    category: 'taste',
    summary: '견과류나 볶은 재료에서 오는 단맛과 고소함의 결합입니다.',
    tasteVector: { sweet: 0.36, fat: 0.36, bitter: 0.12 },
    perceptualVector: { aromaIntensity: 0.44, textureRichness: 0.38, linger: 0.22 },
    dishKindAffinity: { nut: 0.84, dessert: 0.62, sauce: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'spicy-heat',
    label: '매운 열감',
    aliases: ['화한 자극', 'spicy heat'],
    category: 'taste',
    summary: '맛보다 온도감과 자극으로 먼저 느껴지는 매운 인상입니다.',
    tasteVector: { bitter: 0.16, sour: 0.1, salty: 0.08 },
    perceptualVector: { thermalImpact: 0.82, aromaIntensity: 0.38, linger: 0.24 },
    dishKindAffinity: { spice: 0.9, sauce: 0.54, grilled: 0.32 },
    polarity: 'mixed',
  }),
  core({
    id: 'clean-finish',
    label: '깔끔한 마무리',
    aliases: ['깨끗한 피니시', 'clean finish'],
    category: 'finish',
    summary: '입안에 잔여감이 과하게 남지 않고 정리되는 피니시입니다.',
    tasteVector: { sour: 0.18, bitter: 0.12, fat: -0.24 },
    perceptualVector: { cleanFinish: 0.82, brightness: 0.28, heaviness: -0.24 },
    dishKindAffinity: { seafood: 0.62, vegetable: 0.56, broth: 0.52 },
    polarity: 'positive',
  }),
  core({
    id: 'long-linger',
    label: '긴 여운',
    aliases: ['오래 남음', 'long linger'],
    category: 'finish',
    summary: '식사 뒤쪽까지 맛과 향의 인상이 지속되는 신호입니다.',
    tasteVector: { umami: 0.36, bitter: 0.2, fat: 0.22 },
    perceptualVector: { linger: 0.82, aromaIntensity: 0.28, heaviness: 0.18 },
    dishKindAffinity: { meat: 0.58, broth: 0.62, fermented: 0.64 },
    polarity: 'positive',
  }),
  core({
    id: 'short-fade',
    label: '빠르게 사라지는 맛',
    aliases: ['짧은 여운', 'quick fade'],
    category: 'finish',
    summary: '첫 인상은 있으나 뒤쪽으로 오래 이어지지 않는 흐름입니다.',
    tasteVector: { umami: -0.12, fat: -0.12, sour: 0.1 },
    perceptualVector: { linger: -0.46, cleanFinish: 0.3, heaviness: -0.18 },
    dishKindAffinity: { amuse: 0.48, vegetable: 0.4, fruit: 0.44 },
    polarity: 'neutral',
  }),
  core({
    id: 'layered-flow',
    label: '겹겹이 이어지는 흐름',
    aliases: ['층이 있는 맛', 'layered flow'],
    category: 'finish',
    summary: '첫맛, 중반, 끝맛이 차례로 다른 인상을 만드는 구조입니다.',
    tasteVector: { umami: 0.3, sour: 0.14, bitter: 0.14 },
    perceptualVector: { linger: 0.54, aromaIntensity: 0.36, textureRichness: 0.2 },
    dishKindAffinity: { course: 0.7, sauce: 0.52, fermented: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'front-loaded-impact',
    label: '첫입의 선명함',
    aliases: ['처음에 선명함', 'front-loaded impact'],
    category: 'finish',
    summary: '입에 넣는 순간 맛의 방향이 빠르게 읽히는 신호입니다.',
    tasteVector: { sour: 0.2, salty: 0.16, bitter: 0.12 },
    perceptualVector: { brightness: 0.4, aromaIntensity: 0.32, thermalImpact: 0.14 },
    dishKindAffinity: { snack: 0.56, amuse: 0.64, sauce: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'late-bloom',
    label: '뒤로 피어나는 맛',
    aliases: ['뒤로 갈수록 깊어짐', 'late bloom'],
    category: 'finish',
    summary: '초반보다 중후반에 감칠맛이나 향이 서서히 열리는 흐름입니다.',
    tasteVector: { umami: 0.44, fat: 0.18, bitter: 0.12 },
    perceptualVector: { linger: 0.62, aromaIntensity: 0.38, textureRichness: 0.18 },
    dishKindAffinity: { broth: 0.68, meat: 0.54, mushroom: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'palate-cleansing',
    label: '입안을 정리함',
    aliases: ['팔레트 클렌징', 'palate cleansing'],
    category: 'finish',
    summary: '앞선 지방감이나 무게감을 끊고 다음 맛을 받을 수 있게 돕는 신호입니다.',
    tasteVector: { sour: 0.38, bitter: 0.12, fat: -0.26 },
    perceptualVector: { cleanFinish: 0.74, brightness: 0.44, heaviness: -0.32 },
    dishKindAffinity: { vegetable: 0.58, fruit: 0.62, beverage: 0.54 },
    polarity: 'positive',
  }),
  core({
    id: 'finish-pileup',
    label: '끝에 쌓이는 맛',
    aliases: ['마무리 누적감', 'finish pileup'],
    category: 'finish',
    summary: '후반부에 맛과 질감이 겹쳐져 무겁게 남는 신호입니다.',
    tasteVector: { fat: 0.46, umami: 0.28, salty: 0.12 },
    perceptualVector: { heaviness: 0.66, textureRichness: 0.42, cleanFinish: -0.38 },
    dishKindAffinity: { meat: 0.58, fried: 0.62, sauce: 0.52 },
    polarity: 'mixed',
  }),
  core({
    id: 'quiet-finish',
    label: '조용한 피니시',
    aliases: ['은은한 마무리', 'quiet finish'],
    category: 'finish',
    summary: '큰 피크 없이 차분하게 닫히는 마무리입니다.',
    tasteVector: { sweet: 0.08, umami: 0.1, fat: -0.08 },
    perceptualVector: { cleanFinish: 0.42, linger: 0.18, heaviness: -0.16 },
    dishKindAffinity: { tea: 0.42, broth: 0.44, dessert: 0.36 },
    polarity: 'positive',
  }),
  core({
    id: 'bright-transition',
    label: '다음 맛을 여는 산뜻함',
    aliases: ['코스 전환 산미', 'bright transition'],
    category: 'finish',
    summary: '코스 사이에서 다음 접시의 인상을 더 잘 받게 하는 산뜻함입니다.',
    tasteVector: { sour: 0.46, bitter: 0.08, fat: -0.16 },
    perceptualVector: { brightness: 0.62, cleanFinish: 0.6, thermalImpact: 0.12 },
    dishKindAffinity: { course: 0.68, vegetable: 0.54, seafood: 0.4 },
    polarity: 'positive',
  }),
  core({
    id: 'heavy-aftertaste',
    label: '무거운 잔향',
    aliases: ['묵직한 뒷맛', 'heavy aftertaste'],
    category: 'finish',
    summary: '맛과 향이 길게 남지만 입안을 다소 무겁게 만드는 신호입니다.',
    tasteVector: { fat: 0.42, umami: 0.34, bitter: 0.16 },
    perceptualVector: { linger: 0.58, heaviness: 0.58, cleanFinish: -0.26 },
    dishKindAffinity: { meat: 0.66, fermented: 0.48, sauce: 0.52 },
    polarity: 'mixed',
  }),
  core({
    id: 'balanced-arc',
    label: '균형 잡힌 호흡',
    aliases: ['리듬이 좋음', 'balanced arc'],
    category: 'finish',
    summary: '초반, 중반, 마무리의 강도가 자연스럽게 이어지는 흐름입니다.',
    tasteVector: { sweet: 0.12, sour: 0.12, umami: 0.18 },
    perceptualVector: { cleanFinish: 0.34, linger: 0.34, textureRichness: 0.16 },
    dishKindAffinity: { course: 0.72, sauce: 0.42, tasting: 0.64 },
    polarity: 'positive',
  }),
  core({
    id: 'flavor-spike',
    label: '튀는 맛의 피크',
    aliases: ['한 맛이 앞섬', 'flavor spike'],
    category: 'finish',
    summary: '특정 맛이 전체 흐름보다 강하게 튀어나오는 신호입니다.',
    tasteVector: { salty: 0.26, sour: 0.2, bitter: 0.14 },
    perceptualVector: { thermalImpact: 0.22, brightness: 0.24, cleanFinish: -0.08 },
    dishKindAffinity: { sauce: 0.52, pickled: 0.46, spice: 0.42 },
    polarity: 'mixed',
  }),
  core({
    id: 'soft-landing',
    label: '부드러운 마무리',
    aliases: ['소프트 랜딩', 'soft landing'],
    category: 'finish',
    summary: '마지막 인상이 자극 없이 둥글게 닫히는 신호입니다.',
    tasteVector: { sweet: 0.16, fat: 0.12, sour: -0.04 },
    perceptualVector: { cleanFinish: 0.38, textureRichness: 0.22, heaviness: 0.06 },
    dishKindAffinity: { dessert: 0.58, broth: 0.42, dairy: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'persistent-aroma',
    label: '오래 남는 향',
    aliases: ['향의 여운', 'persistent aroma'],
    category: 'finish',
    summary: '맛보다 향의 인상이 길게 남는 피니시입니다.',
    tasteVector: { bitter: 0.12, umami: 0.18, fat: 0.06 },
    perceptualVector: { aromaIntensity: 0.72, linger: 0.58, cleanFinish: 0.08 },
    dishKindAffinity: { herb: 0.58, spice: 0.62, tea: 0.54 },
    polarity: 'positive',
  }),
  core({
    id: 'clean-reset',
    label: '리셋되는 입안',
    aliases: ['입안이 다시 맑아짐', 'clean reset'],
    category: 'finish',
    summary: '먹고 난 뒤 입안의 기준점이 다시 가벼워지는 신호입니다.',
    tasteVector: { sour: 0.24, bitter: 0.1, fat: -0.28 },
    perceptualVector: { cleanFinish: 0.84, brightness: 0.38, heaviness: -0.34 },
    dishKindAffinity: { beverage: 0.58, fruit: 0.56, vegetable: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'silky-texture',
    label: '실키한 질감',
    aliases: ['매끄러운 질감', 'silky texture'],
    category: 'texture',
    summary: '입안에서 결이 부드럽고 매끄럽게 흐르는 질감입니다.',
    tasteVector: { fat: 0.22, sweet: 0.06 },
    perceptualVector: { textureRichness: 0.48, cleanFinish: 0.18, heaviness: 0.12 },
    dishKindAffinity: { sauce: 0.68, fish: 0.42, dessert: 0.48 },
    polarity: 'positive',
  }),
  core({
    id: 'creamy-density',
    label: '크리미한 밀도',
    aliases: ['크림 같은 농도', 'creamy density'],
    category: 'texture',
    summary: '부드럽지만 입안에 밀도 있게 차오르는 질감입니다.',
    tasteVector: { fat: 0.54, sweet: 0.12, umami: 0.08 },
    perceptualVector: { textureRichness: 0.74, heaviness: 0.42, cleanFinish: -0.08 },
    dishKindAffinity: { dairy: 0.8, sauce: 0.66, dessert: 0.6 },
    polarity: 'positive',
  }),
  core({
    id: 'juicy-burst',
    label: '수분감 터짐',
    aliases: ['쥬이시함', 'juicy burst'],
    category: 'texture',
    summary: '씹는 순간 수분과 맛이 함께 퍼지는 질감입니다.',
    tasteVector: { sweet: 0.16, sour: 0.12, umami: 0.1 },
    perceptualVector: { textureRichness: 0.28, brightness: 0.28, aromaIntensity: 0.22 },
    dishKindAffinity: { fruit: 0.7, meat: 0.52, vegetable: 0.48 },
    polarity: 'positive',
  }),
  core({
    id: 'crisp-bite',
    label: '바삭한 식감',
    aliases: ['크리스피함', 'crisp bite'],
    category: 'texture',
    summary: '가볍게 끊기는 소리와 함께 선명한 식감 대비를 만드는 신호입니다.',
    tasteVector: { bitter: 0.08, fat: 0.14, salty: 0.08 },
    perceptualVector: { textureRichness: 0.22, brightness: 0.24, cleanFinish: 0.18 },
    dishKindAffinity: { fried: 0.84, snack: 0.62, vegetable: 0.4 },
    polarity: 'positive',
  }),
  core({
    id: 'chewy-resistance',
    label: '씹는 힘',
    aliases: ['탄력 있는 씹힘', 'chewy resistance'],
    category: 'texture',
    summary: '입안에서 버티는 힘이 있어 식감의 존재감이 커지는 신호입니다.',
    tasteVector: { umami: 0.12, fat: 0.12 },
    perceptualVector: { textureRichness: 0.46, heaviness: 0.24, linger: 0.12 },
    dishKindAffinity: { meat: 0.66, noodle: 0.58, shellfish: 0.44 },
    polarity: 'positive',
  }),
  core({
    id: 'tender-softness',
    label: '부드러운 결',
    aliases: ['연한 식감', 'tender softness'],
    category: 'texture',
    summary: '재료가 힘을 잃지 않으면서도 쉽게 풀리는 부드러움입니다.',
    tasteVector: { fat: 0.16, umami: 0.12 },
    perceptualVector: { textureRichness: 0.32, cleanFinish: 0.18, heaviness: 0.08 },
    dishKindAffinity: { fish: 0.58, meat: 0.62, vegetable: 0.38 },
    polarity: 'positive',
  }),
  core({
    id: 'powdery-dryness',
    label: '분말감 있는 건조함',
    aliases: ['파우더리함', 'powdery dryness'],
    category: 'texture',
    summary: '입안 수분을 가져가며 건조하거나 가루처럼 남는 질감입니다.',
    tasteVector: { bitter: 0.14, sweet: 0.08, fat: -0.08 },
    perceptualVector: { textureRichness: -0.12, cleanFinish: -0.16, thermalImpact: 0.1 },
    dishKindAffinity: { dessert: 0.48, grain: 0.42, powder: 0.7 },
    polarity: 'mixed',
  }),
  core({
    id: 'coating-mouthfeel',
    label: '코팅감',
    aliases: ['입안을 감쌈', 'coating mouthfeel'],
    category: 'texture',
    summary: '소스나 지방이 입안을 감싸며 맛을 붙잡는 질감입니다.',
    tasteVector: { fat: 0.5, umami: 0.18, sweet: 0.08 },
    perceptualVector: { textureRichness: 0.62, heaviness: 0.42, cleanFinish: -0.22 },
    dishKindAffinity: { sauce: 0.8, meat: 0.56, dessert: 0.44 },
    polarity: 'mixed',
  }),
  core({
    id: 'gelatinous-body',
    label: '젤라틴 탄성',
    aliases: ['젤리 같은 탄성', 'gelatinous body'],
    category: 'texture',
    summary: '콜라겐이나 젤이 만드는 흔들리는 바디감입니다.',
    tasteVector: { fat: 0.28, umami: 0.28 },
    perceptualVector: { textureRichness: 0.58, heaviness: 0.28, linger: 0.18 },
    dishKindAffinity: { broth: 0.56, meat: 0.58, dessert: 0.4 },
    polarity: 'positive',
  }),
  core({
    id: 'airy-lightness',
    label: '공기감 있는 가벼움',
    aliases: ['가벼운 질감', 'airy lightness'],
    category: 'texture',
    summary: '부피는 있지만 입안에서 무겁게 남지 않는 질감입니다.',
    tasteVector: { fat: -0.1, sweet: 0.12 },
    perceptualVector: { heaviness: -0.42, cleanFinish: 0.3, textureRichness: 0.16 },
    dishKindAffinity: { dessert: 0.62, foam: 0.72, bread: 0.36 },
    polarity: 'positive',
  }),
  core({
    id: 'dense-chew',
    label: '촘촘한 씹힘',
    aliases: ['밀도 있는 씹힘', 'dense chew'],
    category: 'texture',
    summary: '재료의 조직이 촘촘하게 느껴져 식감의 밀도를 만드는 신호입니다.',
    tasteVector: { umami: 0.14, fat: 0.18 },
    perceptualVector: { textureRichness: 0.6, heaviness: 0.32, linger: 0.16 },
    dishKindAffinity: { meat: 0.7, grain: 0.42, noodle: 0.5 },
    polarity: 'positive',
  }),
  core({
    id: 'fatty-coat',
    label: '지방 코팅감',
    aliases: ['기름 코팅', 'fatty coat'],
    category: 'texture',
    summary: '지방이 입안을 감싸며 맛의 지속 시간을 늘리는 신호입니다.',
    tasteVector: { fat: 0.76, umami: 0.18 },
    perceptualVector: { textureRichness: 0.68, heaviness: 0.58, cleanFinish: -0.36 },
    dishKindAffinity: { meat: 0.78, dairy: 0.62, sauce: 0.58 },
    polarity: 'mixed',
  }),
  core({
    id: 'cool-snap',
    label: '차가운 선명함',
    aliases: ['차갑게 정리됨', 'cool snap'],
    category: 'texture',
    summary: '낮은 온도감이 산미나 향을 또렷하게 보여주는 신호입니다.',
    tasteVector: { sour: 0.24, bitter: 0.08, fat: -0.08 },
    perceptualVector: { thermalImpact: 0.38, brightness: 0.46, cleanFinish: 0.44 },
    dishKindAffinity: { seafood: 0.5, dessert: 0.54, vegetable: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'warm-spread',
    label: '따뜻하게 퍼짐',
    aliases: ['온기가 퍼짐', 'warm spread'],
    category: 'texture',
    summary: '따뜻한 온도감이 향과 감칠맛을 부드럽게 펼치는 신호입니다.',
    tasteVector: { umami: 0.28, fat: 0.16, sweet: 0.08 },
    perceptualVector: { thermalImpact: 0.46, aromaIntensity: 0.32, textureRichness: 0.2 },
    dishKindAffinity: { broth: 0.74, meat: 0.48, sauce: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'crunchy-contrast',
    label: '씹는 대비',
    aliases: ['크런치 대비', 'crunchy contrast'],
    category: 'texture',
    summary: '부드러운 요소 사이에 씹는 소리와 저항을 넣어 리듬을 만드는 신호입니다.',
    tasteVector: { bitter: 0.08, salty: 0.06 },
    perceptualVector: { textureRichness: 0.38, brightness: 0.22, aromaIntensity: 0.12 },
    dishKindAffinity: { garnish: 0.76, fried: 0.58, vegetable: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'soft-broth-body',
    label: '맑은 국물의 바디',
    aliases: ['국물 바디감', 'broth body'],
    category: 'texture',
    summary: '맑아 보이지만 입안에서는 감칠맛과 점도가 은근히 느껴지는 국물 신호입니다.',
    tasteVector: { umami: 0.58, salty: 0.18, fat: 0.08 },
    perceptualVector: { linger: 0.4, textureRichness: 0.28, cleanFinish: 0.3 },
    dishKindAffinity: { broth: 0.9, seafood: 0.48, meat: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'citrus-aroma',
    label: '시트러스 향',
    aliases: ['감귤 향', 'citrus aroma'],
    category: 'aroma',
    summary: '레몬, 라임, 감귤류처럼 밝고 날렵한 향입니다.',
    tasteVector: { sour: 0.34, bitter: 0.06 },
    perceptualVector: { aromaIntensity: 0.62, brightness: 0.58, cleanFinish: 0.36 },
    dishKindAffinity: { seafood: 0.62, dessert: 0.58, beverage: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'herbal-aroma',
    label: '허브 향',
    aliases: ['초록 허브 향', 'herbal aroma'],
    category: 'aroma',
    summary: '허브가 만드는 신선하고 식물적인 향의 선명도입니다.',
    tasteVector: { bitter: 0.18, sour: 0.12 },
    perceptualVector: { aromaIntensity: 0.66, brightness: 0.46, cleanFinish: 0.3 },
    dishKindAffinity: { herb: 0.9, seafood: 0.42, vegetable: 0.58 },
    polarity: 'positive',
  }),
  core({
    id: 'floral-aroma',
    label: '꽃향',
    aliases: ['플로럴 향', 'floral aroma'],
    category: 'aroma',
    summary: '향이 부드럽고 섬세하게 올라오는 꽃 계열 인상입니다.',
    tasteVector: { sweet: 0.12, bitter: 0.04 },
    perceptualVector: { aromaIntensity: 0.58, brightness: 0.3, linger: 0.22 },
    dishKindAffinity: { dessert: 0.54, beverage: 0.48, fruit: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'roasted-aroma',
    label: '구운 향',
    aliases: ['로스티드 향', 'roasted aroma'],
    category: 'aroma',
    summary: '열을 받은 재료에서 오는 고소하고 깊은 향입니다.',
    tasteVector: { bitter: 0.2, umami: 0.22, fat: 0.14 },
    perceptualVector: { aromaIntensity: 0.68, linger: 0.34, textureRichness: 0.2 },
    dishKindAffinity: { roasted: 0.88, meat: 0.58, vegetable: 0.38 },
    polarity: 'positive',
  }),
  core({
    id: 'smoky-aroma',
    label: '훈연 향',
    aliases: ['스모키함', 'smoky aroma'],
    category: 'aroma',
    summary: '연기와 나무 향이 맛의 여운을 길게 만드는 신호입니다.',
    tasteVector: { bitter: 0.28, umami: 0.26, fat: 0.12 },
    perceptualVector: { smoke: 0.82, aromaIntensity: 0.68, linger: 0.42 },
    dishKindAffinity: { smoked: 0.9, meat: 0.66, fish: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'charred-aroma',
    label: '탄 향',
    aliases: ['그을린 향', 'charred aroma'],
    category: 'aroma',
    summary: '그을림에서 오는 쓴맛과 향의 강한 가장자리입니다.',
    tasteVector: { bitter: 0.52, umami: 0.16, fat: 0.08 },
    perceptualVector: { smoke: 0.56, aromaIntensity: 0.54, thermalImpact: 0.14 },
    dishKindAffinity: { grilled: 0.84, meat: 0.58, vegetable: 0.34 },
    polarity: 'mixed',
  }),
  core({
    id: 'seafood-aroma',
    label: '해산물 향',
    aliases: ['바다 향', 'seafood aroma'],
    category: 'aroma',
    summary: '바다, 조개, 생선에서 오는 재료의 향 신호입니다.',
    tasteVector: { umami: 0.36, salty: 0.2, sour: 0.06 },
    perceptualVector: { aromaIntensity: 0.48, cleanFinish: 0.18, linger: 0.22 },
    dishKindAffinity: { seafood: 0.92, shellfish: 0.76, broth: 0.38 },
    polarity: 'neutral',
  }),
  core({
    id: 'meaty-aroma',
    label: '육향',
    aliases: ['고기 향', 'meaty aroma'],
    category: 'aroma',
    summary: '육류의 단백질과 지방에서 오는 깊은 향입니다.',
    tasteVector: { umami: 0.42, fat: 0.28, salty: 0.08 },
    perceptualVector: { aromaIntensity: 0.56, heaviness: 0.36, linger: 0.3 },
    dishKindAffinity: { meat: 0.92, grilled: 0.58, broth: 0.44 },
    polarity: 'positive',
  }),
  core({
    id: 'fermented-aroma',
    label: '발효 향',
    aliases: ['숙성 향', 'fermented aroma'],
    category: 'aroma',
    summary: '발효나 숙성에서 오는 복합적인 향의 깊이입니다.',
    tasteVector: { umami: 0.42, sour: 0.22, salty: 0.12 },
    perceptualVector: { aromaIntensity: 0.72, linger: 0.46, heaviness: 0.18 },
    dishKindAffinity: { fermented: 0.94, sauce: 0.58, dairy: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'earthy-aroma',
    label: '흙내음',
    aliases: ['어시함', 'earthy aroma'],
    category: 'aroma',
    summary: '버섯, 뿌리채소, 곡물에서 오는 땅의 향입니다.',
    tasteVector: { bitter: 0.14, umami: 0.28, sweet: 0.04 },
    perceptualVector: { aromaIntensity: 0.5, linger: 0.3, heaviness: 0.2 },
    dishKindAffinity: { mushroom: 0.82, rootVegetable: 0.64, grain: 0.44 },
    polarity: 'positive',
  }),
  core({
    id: 'nutty-aroma',
    label: '견과 향',
    aliases: ['고소한 향', 'nutty aroma'],
    category: 'aroma',
    summary: '볶은 견과나 씨앗류에서 오는 고소한 향입니다.',
    tasteVector: { fat: 0.28, sweet: 0.14, bitter: 0.1 },
    perceptualVector: { aromaIntensity: 0.58, textureRichness: 0.26, linger: 0.24 },
    dishKindAffinity: { nut: 0.9, dessert: 0.54, grain: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'dairy-aroma',
    label: '유제품 향',
    aliases: ['버터 향', 'dairy aroma'],
    category: 'aroma',
    summary: '버터, 크림, 치즈가 만드는 부드럽고 지방감 있는 향입니다.',
    tasteVector: { fat: 0.42, sweet: 0.08, sour: 0.08 },
    perceptualVector: { aromaIntensity: 0.46, textureRichness: 0.42, heaviness: 0.26 },
    dishKindAffinity: { dairy: 0.9, dessert: 0.58, sauce: 0.62 },
    polarity: 'positive',
  }),
  core({
    id: 'spice-aroma',
    label: '향신료 향',
    aliases: ['스파이스 향', 'spice aroma'],
    category: 'aroma',
    summary: '후추, 씨앗, 향신료에서 오는 방향성과 자극감입니다.',
    tasteVector: { bitter: 0.18, sour: 0.06, salty: 0.04 },
    perceptualVector: { aromaIntensity: 0.72, thermalImpact: 0.36, linger: 0.2 },
    dishKindAffinity: { spice: 0.92, meat: 0.42, sauce: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'broth-aroma',
    label: '육수 향',
    aliases: ['국물 향', 'broth aroma'],
    category: 'aroma',
    summary: '우린 재료가 만드는 따뜻하고 감칠맛 있는 향입니다.',
    tasteVector: { umami: 0.56, salty: 0.16, fat: 0.08 },
    perceptualVector: { aromaIntensity: 0.46, linger: 0.38, thermalImpact: 0.18 },
    dishKindAffinity: { broth: 0.92, meat: 0.44, seafood: 0.44 },
    polarity: 'positive',
  }),
  core({
    id: 'seaweed-aroma',
    label: '해조 향',
    aliases: ['김 향', 'seaweed aroma'],
    category: 'aroma',
    summary: '해조류에서 오는 바다감과 감칠맛의 향 신호입니다.',
    tasteVector: { umami: 0.5, salty: 0.26, bitter: 0.06 },
    perceptualVector: { aromaIntensity: 0.52, cleanFinish: 0.24, linger: 0.24 },
    dishKindAffinity: { seaweed: 0.94, seafood: 0.58, broth: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'fruit-aroma',
    label: '과일 향',
    aliases: ['프루티함', 'fruit aroma'],
    category: 'aroma',
    summary: '과일에서 오는 산뜻함과 단맛의 향 인상입니다.',
    tasteVector: { sweet: 0.24, sour: 0.24 },
    perceptualVector: { aromaIntensity: 0.58, brightness: 0.42, cleanFinish: 0.24 },
    dishKindAffinity: { fruit: 0.92, dessert: 0.62, beverage: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'charcoal-grilled',
    label: '숯불 구이',
    aliases: ['숯향', 'charcoal grilled'],
    category: 'process',
    summary: '숯불에서 오는 훈연감, 그을림, 감칠맛의 조리 신호입니다.',
    tasteVector: { bitter: 0.26, umami: 0.34, fat: 0.16 },
    perceptualVector: { smoke: 0.76, aromaIntensity: 0.58, linger: 0.32 },
    dishKindAffinity: { grilled: 0.96, meat: 0.72, fish: 0.48 },
    recipeNlgTechniqueHints: ['grill', 'charcoal grill', 'barbecue'],
    polarity: 'positive',
  }),
  core({
    id: 'pan-seared',
    label: '팬 시어링',
    aliases: ['시어링', 'pan seared'],
    category: 'process',
    summary: '표면의 마이야르 향과 내부 수분감을 함께 만드는 조리 신호입니다.',
    tasteVector: { umami: 0.3, bitter: 0.12, fat: 0.18 },
    perceptualVector: { aromaIntensity: 0.46, textureRichness: 0.28, linger: 0.18 },
    dishKindAffinity: { meat: 0.7, fish: 0.58, scallop: 0.54 },
    recipeNlgTechniqueHints: ['sear', 'pan sear', 'brown'],
    polarity: 'positive',
  }),
  core({
    id: 'slow-braised',
    label: '장시간 브레이징',
    aliases: ['오래 조림', 'slow braised'],
    category: 'process',
    summary: '시간을 들여 감칠맛, 지방감, 부드러움을 끌어내는 조리 신호입니다.',
    tasteVector: { umami: 0.58, fat: 0.34, salty: 0.14 },
    perceptualVector: { textureRichness: 0.58, heaviness: 0.46, linger: 0.48 },
    dishKindAffinity: { meat: 0.82, sauce: 0.56, broth: 0.5 },
    recipeNlgTechniqueHints: ['braise', 'simmer', 'slow cook'],
    polarity: 'positive',
  }),
  core({
    id: 'steamed-gentle',
    label: '찜의 부드러움',
    aliases: ['찐 질감', 'steamed gentle'],
    category: 'process',
    summary: '재료의 수분과 부드러운 결을 보존하는 조리 신호입니다.',
    tasteVector: { umami: 0.18, fat: -0.04, sour: -0.04 },
    perceptualVector: { textureRichness: 0.22, cleanFinish: 0.36, aromaIntensity: 0.12 },
    dishKindAffinity: { fish: 0.68, vegetable: 0.54, dumpling: 0.5 },
    recipeNlgTechniqueHints: ['steam', 'steamed'],
    polarity: 'positive',
  }),
  core({
    id: 'raw-cured',
    label: '날것/절임의 선명함',
    aliases: ['큐어링', 'raw cured'],
    category: 'process',
    summary: '열을 최소화하고 산미, 염도, 재료향을 또렷하게 보여주는 신호입니다.',
    tasteVector: { sour: 0.26, salty: 0.24, umami: 0.22 },
    perceptualVector: { brightness: 0.46, cleanFinish: 0.42, aromaIntensity: 0.34 },
    dishKindAffinity: { seafood: 0.76, cured: 0.84, vegetable: 0.38 },
    recipeNlgTechniqueHints: ['cure', 'marinate', 'raw'],
    polarity: 'positive',
  }),
  core({
    id: 'pickled-brightness',
    label: '피클링 산뜻함',
    aliases: ['절임 산미', 'pickled brightness'],
    category: 'process',
    summary: '식초나 발효 절임으로 산미와 리셋감을 만드는 조리 신호입니다.',
    tasteVector: { sour: 0.62, salty: 0.18, sweet: 0.08 },
    perceptualVector: { brightness: 0.68, cleanFinish: 0.56, thermalImpact: 0.12 },
    dishKindAffinity: { pickled: 0.94, vegetable: 0.64, garnish: 0.56 },
    recipeNlgTechniqueHints: ['pickle', 'brine', 'marinate'],
    polarity: 'positive',
  }),
  core({
    id: 'fermented-depth',
    label: '발효 숙성',
    aliases: ['숙성 깊이', 'fermented depth'],
    category: 'process',
    summary: '시간과 미생물 작용이 감칠맛과 향의 복합성을 만드는 신호입니다.',
    tasteVector: { umami: 0.66, sour: 0.24, salty: 0.2 },
    perceptualVector: { aromaIntensity: 0.72, linger: 0.54, heaviness: 0.22 },
    dishKindAffinity: { fermented: 0.96, sauce: 0.62, dairy: 0.42 },
    recipeNlgTechniqueHints: ['ferment', 'aged', 'cure'],
    polarity: 'positive',
  }),
  core({
    id: 'smoked-layer',
    label: '훈연층',
    aliases: ['스모크 레이어', 'smoked layer'],
    category: 'process',
    summary: '훈연이 표면과 여운에 향의 층을 만드는 조리 신호입니다.',
    tasteVector: { bitter: 0.24, umami: 0.28, fat: 0.1 },
    perceptualVector: { smoke: 0.82, aromaIntensity: 0.64, linger: 0.46 },
    dishKindAffinity: { smoked: 0.96, meat: 0.66, fish: 0.52 },
    recipeNlgTechniqueHints: ['smoke', 'smoked'],
    polarity: 'positive',
  }),
  core({
    id: 'fried-crispness',
    label: '튀김 바삭함',
    aliases: ['프라이드 크리스프', 'fried crispness'],
    category: 'process',
    summary: '뜨거운 기름이 표면을 바삭하게 만들고 지방감을 더하는 조리 신호입니다.',
    tasteVector: { fat: 0.42, bitter: 0.08, salty: 0.12 },
    perceptualVector: { textureRichness: 0.38, heaviness: 0.22, cleanFinish: -0.08 },
    dishKindAffinity: { fried: 0.96, snack: 0.62, seafood: 0.42 },
    recipeNlgTechniqueHints: ['fry', 'deep fry', 'pan fry'],
    polarity: 'positive',
  }),
  core({
    id: 'confit-richness',
    label: '콩피 지방감',
    aliases: ['기름에 익힌 부드러움', 'confit richness'],
    category: 'process',
    summary: '지방 속에서 천천히 익혀 부드러움과 코팅감을 만드는 조리 신호입니다.',
    tasteVector: { fat: 0.68, umami: 0.22 },
    perceptualVector: { textureRichness: 0.68, heaviness: 0.52, cleanFinish: -0.24 },
    dishKindAffinity: { meat: 0.72, poultry: 0.66, vegetable: 0.34 },
    recipeNlgTechniqueHints: ['confit', 'cook in fat'],
    polarity: 'mixed',
  }),
  core({
    id: 'roasted-concentration',
    label: '로스팅 농축',
    aliases: ['구워 농축됨', 'roasted concentration'],
    category: 'process',
    summary: '수분이 줄고 단맛, 쓴맛, 향이 응축되는 조리 신호입니다.',
    tasteVector: { sweet: 0.22, bitter: 0.18, umami: 0.24 },
    perceptualVector: { aromaIntensity: 0.58, textureRichness: 0.24, linger: 0.28 },
    dishKindAffinity: { roasted: 0.94, vegetable: 0.56, meat: 0.48 },
    recipeNlgTechniqueHints: ['roast', 'oven roast'],
    polarity: 'positive',
  }),
  core({
    id: 'cold-infused',
    label: '차가운 인퓨전',
    aliases: ['콜드 인퓨전', 'cold infused'],
    category: 'process',
    summary: '차가운 온도에서 향을 맑게 우려내는 조리/추출 신호입니다.',
    tasteVector: { sour: 0.12, bitter: 0.08, sweet: 0.06 },
    perceptualVector: { aromaIntensity: 0.42, brightness: 0.42, cleanFinish: 0.48 },
    dishKindAffinity: { beverage: 0.72, dessert: 0.42, herb: 0.52 },
    recipeNlgTechniqueHints: ['infuse', 'steep', 'cold brew'],
    polarity: 'positive',
  }),
  core({
    id: 'broth-reduction',
    label: '육수 농축',
    aliases: ['리덕션', 'broth reduction'],
    category: 'process',
    summary: '액체를 줄여 감칠맛과 농도를 집중시키는 조리 신호입니다.',
    tasteVector: { umami: 0.68, salty: 0.24, fat: 0.12 },
    perceptualVector: { linger: 0.58, textureRichness: 0.36, heaviness: 0.32 },
    dishKindAffinity: { broth: 0.82, sauce: 0.76, meat: 0.42 },
    recipeNlgTechniqueHints: ['reduce', 'simmer', 'concentrate'],
    polarity: 'positive',
  }),
  core({
    id: 'emulsified-sauce',
    label: '유화 소스감',
    aliases: ['에멀전 소스', 'emulsified sauce'],
    category: 'process',
    summary: '지방과 수분이 결합해 부드러운 코팅감과 산미 균형을 만드는 소스 신호입니다.',
    tasteVector: { fat: 0.42, sour: 0.18, sweet: 0.06 },
    perceptualVector: { textureRichness: 0.56, cleanFinish: 0.08, heaviness: 0.22 },
    dishKindAffinity: { sauce: 0.94, seafood: 0.46, vegetable: 0.38 },
    recipeNlgTechniqueHints: ['emulsify', 'whisk', 'blend'],
    polarity: 'positive',
  }),
  core({
    id: 'charred-edge',
    label: '그을린 가장자리',
    aliases: ['차드 엣지', 'charred edge'],
    category: 'process',
    summary: '재료 표면 일부가 그을려 쓴맛과 향의 대비를 만드는 조리 신호입니다.',
    tasteVector: { bitter: 0.46, umami: 0.2, sweet: 0.06 },
    perceptualVector: { smoke: 0.48, aromaIntensity: 0.5, textureRichness: 0.18 },
    dishKindAffinity: { grilled: 0.82, vegetable: 0.46, meat: 0.58 },
    recipeNlgTechniqueHints: ['char', 'broil', 'blacken'],
    polarity: 'mixed',
  }),
  core({
    id: 'sous-vide-tenderness',
    label: '저온조리 부드러움',
    aliases: ['수비드 텐더', 'sous-vide tenderness'],
    category: 'process',
    summary: '정밀한 온도 제어로 재료의 수분과 부드러움을 유지하는 조리 신호입니다.',
    tasteVector: { umami: 0.18, fat: 0.12 },
    perceptualVector: { textureRichness: 0.38, cleanFinish: 0.18, heaviness: 0.08 },
    dishKindAffinity: { meat: 0.62, fish: 0.58, poultry: 0.5 },
    recipeNlgTechniqueHints: ['sous vide', 'low temperature'],
    polarity: 'positive',
  }),
  core({
    id: 'white-fish-clean',
    label: '흰살 생선의 맑음',
    aliases: ['담백한 생선', 'white fish clean'],
    category: 'ingredient',
    summary: '흰살 생선에서 자주 기대되는 맑은 감칠맛과 부드러운 결입니다.',
    tasteVector: { umami: 0.38, salty: 0.12, fat: -0.04 },
    perceptualVector: { cleanFinish: 0.48, textureRichness: 0.2, brightness: 0.16 },
    dishKindAffinity: { fish: 0.9, seafood: 0.82, steamed: 0.48 },
    foodOnHints: ['fish food product'],
    polarity: 'positive',
  }),
  core({
    id: 'blue-fish-oil',
    label: '등푸른 생선 지방감',
    aliases: ['고등어 지방감', 'blue fish oil'],
    category: 'ingredient',
    summary: '등푸른 생선에서 오는 선명한 지방감과 바다 향입니다.',
    tasteVector: { fat: 0.54, umami: 0.38, salty: 0.14 },
    perceptualVector: { heaviness: 0.42, aromaIntensity: 0.46, linger: 0.32 },
    dishKindAffinity: { fish: 0.88, seafood: 0.78, grilled: 0.54 },
    foodOnHints: ['fish food product'],
    polarity: 'mixed',
  }),
  core({
    id: 'shellfish-sweetness',
    label: '조개류 단맛',
    aliases: ['패류 단맛', 'shellfish sweetness'],
    category: 'ingredient',
    summary: '조개류에서 오는 은은한 단맛과 해수감입니다.',
    tasteVector: { sweet: 0.28, umami: 0.42, salty: 0.22 },
    perceptualVector: { cleanFinish: 0.32, aromaIntensity: 0.3, linger: 0.22 },
    dishKindAffinity: { shellfish: 0.94, seafood: 0.86, broth: 0.5 },
    foodOnHints: ['shellfish food product'],
    polarity: 'positive',
  }),
  core({
    id: 'crustacean-umami',
    label: '갑각류 감칠맛',
    aliases: ['새우 감칠맛', 'crustacean umami'],
    category: 'ingredient',
    summary: '새우, 게 등 갑각류에서 오는 달큰한 감칠맛입니다.',
    tasteVector: { umami: 0.58, sweet: 0.24, salty: 0.12 },
    perceptualVector: { aromaIntensity: 0.34, linger: 0.36, textureRichness: 0.18 },
    dishKindAffinity: { crustacean: 0.94, seafood: 0.86, sauce: 0.46 },
    foodOnHints: ['crustacean food product'],
    polarity: 'positive',
  }),
  core({
    id: 'beef-fat-depth',
    label: '소고기 지방 깊이',
    aliases: ['한우 지방감', 'beef fat depth'],
    category: 'ingredient',
    summary: '소고기 지방과 육향이 만드는 깊고 긴 여운입니다.',
    tasteVector: { fat: 0.62, umami: 0.5, salty: 0.08 },
    perceptualVector: { heaviness: 0.58, textureRichness: 0.52, linger: 0.46 },
    dishKindAffinity: { beef: 0.96, meat: 0.9, grilled: 0.62 },
    foodOnHints: ['beef food product'],
    polarity: 'positive',
  }),
  core({
    id: 'pork-savory-fat',
    label: '돼지고기 감칠 지방',
    aliases: ['돼지 지방감', 'pork savory fat'],
    category: 'ingredient',
    summary: '돼지고기 지방이 주는 둥근 감칠맛과 코팅감입니다.',
    tasteVector: { fat: 0.58, umami: 0.42, sweet: 0.06 },
    perceptualVector: { textureRichness: 0.54, heaviness: 0.46, linger: 0.3 },
    dishKindAffinity: { pork: 0.96, meat: 0.86, braised: 0.54 },
    foodOnHints: ['pork food product'],
    polarity: 'positive',
  }),
  core({
    id: 'poultry-clean-meat',
    label: '닭/가금류 담백함',
    aliases: ['닭고기 담백함', 'poultry clean meat'],
    category: 'ingredient',
    summary: '가금류에서 오는 비교적 깨끗한 육향과 담백한 감칠맛입니다.',
    tasteVector: { umami: 0.32, fat: 0.12, salty: 0.08 },
    perceptualVector: { cleanFinish: 0.34, textureRichness: 0.18, aromaIntensity: 0.22 },
    dishKindAffinity: { poultry: 0.96, meat: 0.64, broth: 0.42 },
    foodOnHints: ['poultry food product'],
    polarity: 'positive',
  }),
  core({
    id: 'mushroom-earthy-umami',
    label: '버섯 흙내음 감칠맛',
    aliases: ['버섯 감칠맛', 'mushroom earthy umami'],
    category: 'ingredient',
    summary: '버섯에서 오는 흙내음과 깊은 감칠맛의 조합입니다.',
    tasteVector: { umami: 0.62, bitter: 0.12, sweet: 0.04 },
    perceptualVector: { aromaIntensity: 0.5, linger: 0.42, heaviness: 0.22 },
    dishKindAffinity: { mushroom: 0.96, vegetable: 0.54, broth: 0.44 },
    foodOnHints: ['fungus food product'],
    polarity: 'positive',
  }),
  core({
    id: 'root-vegetable-sweetness',
    label: '뿌리채소 단맛',
    aliases: ['근채 단맛', 'root vegetable sweetness'],
    category: 'ingredient',
    summary: '뿌리채소가 익으며 만들어내는 둥근 단맛입니다.',
    tasteVector: { sweet: 0.38, umami: 0.14, bitter: 0.06 },
    perceptualVector: { textureRichness: 0.24, heaviness: 0.12, cleanFinish: 0.18 },
    dishKindAffinity: { rootVegetable: 0.94, vegetable: 0.78, roasted: 0.5 },
    foodOnHints: ['root vegetable food product'],
    polarity: 'positive',
  }),
  core({
    id: 'leafy-green-bitterness',
    label: '잎채소 쓴맛',
    aliases: ['채소 쓴맛', 'leafy green bitterness'],
    category: 'ingredient',
    summary: '잎채소에서 오는 풋풋함과 쓴맛의 가장자리입니다.',
    tasteVector: { bitter: 0.42, sour: 0.1, sweet: -0.04 },
    perceptualVector: { brightness: 0.38, cleanFinish: 0.34, aromaIntensity: 0.28 },
    dishKindAffinity: { leafyGreen: 0.94, vegetable: 0.82, salad: 0.6 },
    foodOnHints: ['leaf vegetable food product'],
    polarity: 'mixed',
  }),
  core({
    id: 'berry-acid-sweet',
    label: '과실 산미 단맛',
    aliases: ['베리 산미', 'berry acid sweet'],
    category: 'ingredient',
    summary: '베리류나 산미 있는 과일에서 오는 단맛과 산미의 대비입니다.',
    tasteVector: { sour: 0.46, sweet: 0.34, bitter: 0.04 },
    perceptualVector: { brightness: 0.56, aromaIntensity: 0.46, cleanFinish: 0.34 },
    dishKindAffinity: { fruit: 0.92, dessert: 0.72, beverage: 0.44 },
    foodOnHints: ['berry food product'],
    polarity: 'positive',
  }),
  core({
    id: 'chocolate-bitter-sweet',
    label: '초콜릿 쓴단맛',
    aliases: ['카카오 쓴단맛', 'chocolate bitter sweet'],
    category: 'ingredient',
    summary: '카카오의 쓴맛과 단맛, 지방감이 함께 만드는 디저트 신호입니다.',
    tasteVector: { bitter: 0.42, sweet: 0.34, fat: 0.32 },
    perceptualVector: { textureRichness: 0.54, linger: 0.4, heaviness: 0.28 },
    dishKindAffinity: { chocolate: 0.96, dessert: 0.86, dairy: 0.34 },
    foodOnHints: ['chocolate food product'],
    polarity: 'positive',
  }),
  core({
    id: 'sweet-acid-balance',
    label: '단맛과 산미 균형',
    aliases: ['새콤달콤 균형', 'sweet acid balance'],
    category: 'composition',
    summary: '단맛과 산미가 서로를 눌러주며 밝은 균형을 만드는 구성 신호입니다.',
    tasteVector: { sweet: 0.34, sour: 0.34 },
    perceptualVector: { brightness: 0.44, cleanFinish: 0.34, aromaIntensity: 0.18 },
    dishKindAffinity: { dessert: 0.76, fruit: 0.72, sauce: 0.42 },
    polarity: 'positive',
  }),
  core({
    id: 'fat-acid-balance',
    label: '지방감과 산미 균형',
    aliases: ['기름짐을 잡는 산미', 'fat acid balance'],
    category: 'composition',
    summary: '지방감이 주는 풍성함을 산미가 정리해주는 구성 신호입니다.',
    tasteVector: { fat: 0.38, sour: 0.34, umami: 0.12 },
    perceptualVector: { textureRichness: 0.34, cleanFinish: 0.38, heaviness: 0.14 },
    dishKindAffinity: { sauce: 0.76, meat: 0.58, seafood: 0.46 },
    polarity: 'positive',
  }),
  core({
    id: 'umami-salt-balance',
    label: '감칠맛과 간의 균형',
    aliases: ['간과 감칠 균형', 'umami salt balance'],
    category: 'composition',
    summary: '짠맛이 튀지 않고 감칠맛을 길게 만드는 구성 신호입니다.',
    tasteVector: { umami: 0.42, salty: 0.28 },
    perceptualVector: { linger: 0.38, cleanFinish: 0.24, heaviness: 0.14 },
    dishKindAffinity: { broth: 0.7, sauce: 0.72, meat: 0.44 },
    polarity: 'positive',
  }),
  core({
    id: 'aroma-texture-alignment',
    label: '향과 질감의 정렬',
    aliases: ['향과 식감이 맞음', 'aroma texture alignment'],
    category: 'composition',
    summary: '향의 방향과 질감의 무게가 어긋나지 않고 함께 읽히는 구성 신호입니다.',
    tasteVector: { umami: 0.14, fat: 0.12, sour: 0.08 },
    perceptualVector: { aromaIntensity: 0.36, textureRichness: 0.34, cleanFinish: 0.2 },
    dishKindAffinity: { course: 0.72, sauce: 0.52, tasting: 0.58 },
    polarity: 'positive',
  }),
] as const satisfies readonly TbaCoreTasteLexiconEntry[];

export const TBA_CORE_TASTE_LEXICON_VERSION = '0.1';
export const TBA_CORE_TASTE_LEXICON_MIN_ACTIVE_CONFIDENCE = 0.72;
