import type { TbaFoodOntologyBridgeEntry } from '../types/tbaFoodOntology';

const foodOn = (
  entry: TbaFoodOntologyBridgeEntry,
): TbaFoodOntologyBridgeEntry => entry;

export const TBA_FOODON_BRIDGE_VERSION = '0.1';
export const TBA_FOODON_REFERENCE_PATH = 'data/foodon/foodon-master';
export const TBA_FOODON_REFERENCE_LICENSE = 'CC BY 4.0';

export const TBA_FOODON_BRIDGE_ENTRIES: readonly TbaFoodOntologyBridgeEntry[] = [
  foodOn({
    aliases: ['흰살생선', 'white fish', '생선', '도미', '광어', '농어', '담백한 생선'],
    canonicalName: 'white fish',
    description: '맑은 감칠맛과 부드러운 결을 중심으로 읽는 흰살 생선 재료군입니다.',
    dishKindIds: ['seafood'],
    familyId: 'fish',
    id: 'foodon-bridge:ingredient:white-fish',
    kind: 'ingredient',
    koName: '흰살 생선',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:white-fish', 'lexicon:white-fish-clean'],
  }),
  foodOn({
    aliases: ['등푸른 생선', '기름진 생선', 'blue fish', 'oily fish', '고등어', '방어', '참치'],
    canonicalName: 'oily fish',
    description: '지방감과 해산물 향이 뚜렷하게 올라오는 생선 재료군입니다.',
    dishKindIds: ['seafood'],
    familyId: 'fish',
    id: 'foodon-bridge:ingredient:oily-fish',
    kind: 'ingredient',
    koName: '기름진 생선',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:oily-fish', 'lexicon:blue-fish-oil'],
  }),
  foodOn({
    aliases: ['패류', '조개', 'shellfish', '굴', '가리비', '백합'],
    canonicalName: 'shellfish',
    description: '해수 감칠맛과 은근한 단맛을 함께 읽는 패류 재료군입니다.',
    dishKindIds: ['seafood'],
    familyId: 'shellfish',
    id: 'foodon-bridge:ingredient:shellfish',
    kind: 'ingredient',
    koName: '패류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:shellfish', 'lexicon:shellfish-sweetness', 'lexicon:briny-sea'],
  }),
  foodOn({
    aliases: ['갑각류', 'crustacean', '새우', '게', '랍스터'],
    canonicalName: 'crustacean',
    description: '갑각류 특유의 단맛, 향, 감칠맛을 읽는 재료군입니다.',
    dishKindIds: ['seafood'],
    familyId: 'crustacean',
    id: 'foodon-bridge:ingredient:crustacean',
    kind: 'ingredient',
    koName: '갑각류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:crustacean', 'lexicon:shellfish-sweetness', 'lexicon:seafood-aroma'],
  }),
  foodOn({
    aliases: ['표고', '표고버섯', 'shiitake', 'shiitake mushroom', '香菇'],
    canonicalName: 'shiitake mushroom',
    description: '버섯의 흙내, 구수함, 감칠맛을 선명하게 보여주는 재료 신호입니다.',
    dishKindIds: ['vegetable_herb', 'broth'],
    familyId: 'mushroom',
    id: 'foodon-bridge:ingredient:shiitake',
    kind: 'ingredient',
    koName: '표고버섯',
    parentIds: ['foodon-bridge:ingredient:mushroom'],
    source: 'FoodOn-reference',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:mushroom', 'lexicon:mushroom-earthy-umami'],
  }),
  foodOn({
    aliases: ['버섯', 'mushroom', 'mushroom fruitbody', '양송이', '송이', '트러플'],
    canonicalName: 'mushroom fruitbody',
    description: '흙내, 구수함, 감칠맛의 낮은 층을 읽는 버섯 재료군입니다.',
    dishKindIds: ['vegetable_herb', 'broth'],
    familyId: 'mushroom',
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_00003528',
    id: 'foodon-bridge:ingredient:mushroom',
    kind: 'ingredient',
    koName: '버섯',
    source: 'FoodOn-reference',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:mushroom', 'lexicon:mushroom-earthy-umami'],
  }),
  foodOn({
    aliases: ['잎채소', 'leafy green', '나물', '봄동', '허브', '샐러드'],
    canonicalName: 'leafy green vegetable',
    description: '초록 향, 쌉싸름함, 산뜻한 질감을 읽는 채소 재료군입니다.',
    dishKindIds: ['vegetable_herb'],
    familyId: 'vegetable',
    id: 'foodon-bridge:ingredient:leafy-green',
    kind: 'ingredient',
    koName: '잎채소',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:leafy-green', 'lexicon:leafy-green-bitterness', 'lexicon:green-freshness'],
  }),
  foodOn({
    aliases: ['뿌리채소', 'root vegetable', '더덕', '무', '당근', '비트'],
    canonicalName: 'root vegetable',
    description: '흙내, 단맛, 구운 향을 함께 읽는 뿌리채소 재료군입니다.',
    dishKindIds: ['vegetable_herb'],
    familyId: 'vegetable',
    id: 'foodon-bridge:ingredient:root-vegetable',
    kind: 'ingredient',
    koName: '뿌리채소',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:root-vegetable', 'lexicon:root-vegetable-sweetness'],
  }),
  foodOn({
    aliases: ['소고기', '한우', 'beef', '채끝', '안심', '등심'],
    canonicalName: 'beef',
    description: '육향, 지방감, 감칠맛의 밀도를 읽는 육류 재료군입니다.',
    dishKindIds: ['meat'],
    familyId: 'meat',
    id: 'foodon-bridge:ingredient:beef',
    kind: 'ingredient',
    koName: '소고기',
    source: 'FoodOn-reference',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:beef', 'lexicon:beef-fat-depth'],
  }),
  foodOn({
    aliases: ['돼지고기', '돼지', 'pork', '삼겹', '목살'],
    canonicalName: 'pork',
    description: '돼지고기의 지방감, 단맛, 구운 향을 읽는 육류 재료군입니다.',
    dishKindIds: ['meat'],
    familyId: 'meat',
    id: 'foodon-bridge:ingredient:pork',
    kind: 'ingredient',
    koName: '돼지고기',
    source: 'FoodOn-reference',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:pork', 'lexicon:pork-savory-fat'],
  }),
  foodOn({
    aliases: ['양고기', '양갈비', 'lamb'],
    canonicalName: 'lamb',
    description: '양고기의 향, 지방감, 허브/훈연과의 결합을 읽는 육류 재료군입니다.',
    dishKindIds: ['meat'],
    familyId: 'meat',
    id: 'foodon-bridge:ingredient:lamb',
    kind: 'ingredient',
    koName: '양고기',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:lamb', 'lexicon:meaty-aroma'],
  }),
  foodOn({
    aliases: ['가금류', '닭', '오리', 'poultry', 'duck', 'chicken'],
    canonicalName: 'poultry',
    description: '닭과 오리처럼 육향이 비교적 섬세한 가금류 재료군입니다.',
    dishKindIds: ['meat'],
    familyId: 'meat',
    id: 'foodon-bridge:ingredient:poultry',
    kind: 'ingredient',
    koName: '가금류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:poultry', 'lexicon:poultry-clean-meat'],
  }),
  foodOn({
    aliases: ['곡물', 'grain', '쌀', '보리', '메밀', '빵'],
    canonicalName: 'grain',
    description: '구수함, 전분감, 포만감의 바닥을 읽는 곡물 재료군입니다.',
    dishKindIds: ['grain_noodle'],
    familyId: 'grain',
    id: 'foodon-bridge:ingredient:grain',
    kind: 'ingredient',
    koName: '곡물',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:grain', 'lexicon:savory-depth'],
  }),
  foodOn({
    aliases: ['면', 'noodle', '파스타', '국수', '카펠리니'],
    canonicalName: 'noodle',
    description: '면의 탄력, 온도감, 소스 흡착을 읽는 재료군입니다.',
    dishKindIds: ['grain_noodle'],
    familyId: 'grain',
    id: 'foodon-bridge:ingredient:noodle',
    kind: 'ingredient',
    koName: '면',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:noodle', 'lexicon:chewy-resistance'],
  }),
  foodOn({
    aliases: ['과일', 'fruit', '오미자', '감귤', '딸기', '배'],
    canonicalName: 'fruit',
    description: '과일 향, 산미, 단맛의 균형을 읽는 재료군입니다.',
    dishKindIds: ['dessert', 'beverage_pairing'],
    familyId: 'fruit',
    id: 'foodon-bridge:ingredient:fruit',
    kind: 'ingredient',
    koName: '과일',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:fruit', 'lexicon:fruit-aroma', 'lexicon:bright-acidity'],
  }),
  foodOn({
    aliases: ['유제품', 'dairy', '크림', '치즈', '요거트', '버터'],
    canonicalName: 'dairy food product',
    description: '유제품의 지방감, 산미, 부드러운 질감을 읽는 재료군입니다.',
    dishKindIds: ['dessert'],
    familyId: 'dairy',
    id: 'foodon-bridge:ingredient:dairy',
    kind: 'ingredient',
    koName: '유제품',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:dairy', 'lexicon:lactic-tang', 'lexicon:creamy-density'],
  }),
  foodOn({
    aliases: ['초콜릿', 'chocolate', '카카오', '코코아'],
    canonicalName: 'chocolate food product',
    description: '초콜릿의 쓴단맛과 지방감, 긴 여운을 읽는 재료군입니다.',
    dishKindIds: ['dessert'],
    familyId: 'cacao',
    id: 'foodon-bridge:ingredient:chocolate',
    kind: 'ingredient',
    koName: '초콜릿',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:chocolate', 'lexicon:chocolate-bitter-sweet'],
  }),
  foodOn({
    aliases: ['차', 'tea', '티', '우롱', '녹차', '홍차'],
    canonicalName: 'tea beverage',
    description: '차의 향, 쌉싸름함, 페어링 후미를 읽는 음료 재료군입니다.',
    dishKindIds: ['beverage_pairing'],
    familyId: 'beverage',
    id: 'foodon-bridge:ingredient:tea',
    kind: 'ingredient',
    koName: '차',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:tea', 'lexicon:astringent-bitterness', 'lexicon:quiet-finish'],
  }),
  foodOn({
    aliases: ['달걀', '계란', 'egg', '노른자', '흰자'],
    canonicalName: 'egg',
    description: '부드러운 지방감과 둥근 단맛, 유화감을 만드는 보편 재료입니다.',
    dishKindIds: ['meat', 'dessert'],
    familyId: 'animal-product',
    id: 'foodon-bridge:ingredient:egg',
    kind: 'ingredient',
    koName: '달걀',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:egg', 'lexicon:mellow-sweetness', 'lexicon:creamy-density'],
  }),
  foodOn({
    aliases: ['두부', '콩', 'soy', 'tofu', '콩물', '두유'],
    canonicalName: 'soybean food product',
    description: '담백한 고소함, 부드러운 결, 낮은 감칠맛을 만드는 콩/두부 재료군입니다.',
    dishKindIds: ['vegetable_herb'],
    familyId: 'legume',
    id: 'foodon-bridge:ingredient:soy-tofu',
    kind: 'ingredient',
    koName: '콩/두부',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:soy-tofu', 'lexicon:clear-umami', 'lexicon:tender-softness'],
  }),
  foodOn({
    aliases: ['오징어', '문어', '한치', '낙지', 'squid', 'octopus', 'cephalopod'],
    canonicalName: 'cephalopod food product',
    description: '탄력 있는 식감과 해산물 감칠맛, 깨끗한 짠맛을 읽는 두족류 재료군입니다.',
    dishKindIds: ['seafood'],
    familyId: 'seafood',
    id: 'foodon-bridge:ingredient:cephalopod',
    kind: 'ingredient',
    koName: '오징어/문어',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:cephalopod', 'lexicon:seafood-aroma', 'lexicon:chewy-resistance'],
  }),
  foodOn({
    aliases: ['해조류', '김', '다시마', '미역', 'seaweed', 'kelp'],
    canonicalName: 'seaweed food product',
    description: '바다 향, 미네랄 짠맛, 맑은 감칠맛을 주는 해조류 재료군입니다.',
    dishKindIds: ['seafood', 'broth'],
    familyId: 'seaweed',
    id: 'foodon-bridge:ingredient:seaweed',
    kind: 'ingredient',
    koName: '해조류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:seaweed', 'lexicon:seaweed-aroma', 'lexicon:briny-sea'],
  }),
  foodOn({
    aliases: ['마늘', '양파', '대파', '쪽파', 'allium', 'garlic', 'onion', 'scallion'],
    canonicalName: 'allium vegetable',
    description: '생으로는 향신감, 익히면 단맛과 구운 향을 만드는 보편 향채입니다.',
    dishKindIds: ['vegetable_herb'],
    familyId: 'allium',
    id: 'foodon-bridge:ingredient:allium',
    kind: 'ingredient',
    koName: '마늘/양파류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:allium', 'lexicon:spice-aroma', 'lexicon:caramel-sweetness'],
  }),
  foodOn({
    aliases: ['토마토', 'tomato', '방울토마토'],
    canonicalName: 'tomato food product',
    description: '산미, 감칠맛, 과실 단맛을 함께 제공하는 보편 채소/과실 재료입니다.',
    dishKindIds: ['vegetable_herb'],
    familyId: 'fruit-vegetable',
    id: 'foodon-bridge:ingredient:tomato',
    kind: 'ingredient',
    koName: '토마토',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:tomato', 'lexicon:bright-acidity', 'lexicon:sweet-acid-balance'],
  }),
  foodOn({
    aliases: ['감자', '고구마', '전분', 'potato', 'sweet potato', 'starch'],
    canonicalName: 'potato and starch food product',
    description: '포슬함, 전분감, 둥근 단맛, 포만감을 만드는 보편 뿌리/전분 재료군입니다.',
    dishKindIds: ['vegetable_herb', 'grain_noodle'],
    familyId: 'starch',
    id: 'foodon-bridge:ingredient:potato-starch',
    kind: 'ingredient',
    koName: '감자/전분류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:potato-starch', 'lexicon:root-vegetable-sweetness', 'lexicon:powdery-dryness'],
  }),
  foodOn({
    aliases: ['양배추', '배추', '브로콜리', '콜리플라워', 'cabbage', 'brassica'],
    canonicalName: 'brassica vegetable',
    description: '생으로는 풋내와 쌉싸름함, 익히면 부드러운 단맛을 주는 보편 채소군입니다.',
    dishKindIds: ['vegetable_herb'],
    familyId: 'vegetable',
    id: 'foodon-bridge:ingredient:brassica',
    kind: 'ingredient',
    koName: '배추/양배추류',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:brassica', 'lexicon:green-freshness', 'lexicon:mellow-sweetness'],
  }),
  foodOn({
    aliases: ['쌀', '밥', 'rice', '누룽지', '리조또'],
    canonicalName: 'rice food product',
    description: '전분감, 은은한 단맛, 구수한 깊이를 만드는 일상 곡물입니다.',
    dishKindIds: ['grain_noodle'],
    familyId: 'grain',
    id: 'foodon-bridge:ingredient:rice',
    kind: 'ingredient',
    koName: '쌀',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:rice', 'lexicon:savory-depth', 'lexicon:soft-landing'],
  }),
  foodOn({
    aliases: ['밀', '밀가루', '빵', '면', 'wheat', 'flour', 'bread'],
    canonicalName: 'wheat food product',
    description: '탄력, 구운 향, 고소함을 만드는 밀 기반 재료군입니다.',
    dishKindIds: ['grain_noodle'],
    familyId: 'grain',
    id: 'foodon-bridge:ingredient:wheat',
    kind: 'ingredient',
    koName: '밀',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:wheat', 'lexicon:chewy-resistance', 'lexicon:roasted-aroma'],
  }),
  foodOn({
    aliases: ['견과', '깨', '참깨', '들깨', 'nut', 'seed', 'sesame', 'perilla'],
    canonicalName: 'nut or seed food product',
    description: '고소한 향, 지방감, 긴 여운을 만드는 견과와 씨앗류 재료군입니다.',
    dishKindIds: ['dessert', 'grain_noodle'],
    familyId: 'nut-seed',
    id: 'foodon-bridge:ingredient:nut-seed',
    kind: 'ingredient',
    koName: '견과/씨앗',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:nut-seed', 'lexicon:nutty-aroma', 'lexicon:nutty-sweetness'],
  }),
  foodOn({
    aliases: ['참기름', '들기름', 'sesame oil', 'perilla oil'],
    canonicalName: 'seed oil',
    description: '씨앗 기름의 고소한 향, 지방 코팅감, 후미를 만드는 보편 양념입니다.',
    dishKindIds: ['vegetable_herb', 'grain_noodle'],
    familyId: 'oil',
    id: 'foodon-bridge:ingredient:seed-oil',
    kind: 'ingredient',
    koName: '참기름/들기름',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:seed-oil', 'lexicon:nutty-aroma', 'lexicon:fatty-coat'],
  }),
  foodOn({
    aliases: ['간장', '된장', '미소', 'soy sauce', 'doenjang', 'miso'],
    canonicalName: 'fermented soy seasoning',
    description: '발효 감칠맛, 짠맛, 장 향을 만드는 보편 발효 양념입니다.',
    dishKindIds: ['fermented_jang'],
    familyId: 'jang',
    id: 'foodon-bridge:ingredient:soy-jang',
    kind: 'ingredient',
    koName: '간장/된장',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:soy-jang', 'lexicon:fermented-umami', 'lexicon:rounded-salinity', 'lexicon:fermented-aroma'],
  }),
  foodOn({
    aliases: ['고추장', '고춧가루', 'gochujang', 'chili paste', 'chili powder'],
    canonicalName: 'chili fermented seasoning',
    description: '발효 감칠맛, 단맛, 매운 열감을 함께 주는 보편 양념입니다.',
    dishKindIds: ['fermented_jang'],
    familyId: 'jang',
    id: 'foodon-bridge:ingredient:chili-jang',
    kind: 'ingredient',
    koName: '고추장/고추',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:chili-jang', 'lexicon:spicy-heat', 'lexicon:fermented-umami'],
  }),
  foodOn({
    aliases: ['식초', '초', 'vinegar', 'acid seasoning'],
    canonicalName: 'vinegar',
    description: '선명한 산미와 절임감, 입안을 정리하는 효과를 주는 보편 산미 양념입니다.',
    dishKindIds: ['fermented_jang'],
    familyId: 'acid-seasoning',
    id: 'foodon-bridge:ingredient:vinegar',
    kind: 'ingredient',
    koName: '식초',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:vinegar', 'lexicon:sharp-acidity', 'lexicon:palate-cleansing', 'lexicon:pickled-brightness'],
  }),
  foodOn({
    aliases: ['커피', 'coffee', '에스프레소', '콜드브루'],
    canonicalName: 'coffee beverage',
    description: '볶은 향, 쓴맛, 산미, 긴 여운을 읽는 보편 음료 신호입니다.',
    dishKindIds: ['beverage_pairing', 'dessert'],
    familyId: 'beverage',
    id: 'foodon-bridge:ingredient:coffee',
    kind: 'ingredient',
    koName: '커피',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-material',
    tbaSignalIds: ['ingredient:coffee', 'lexicon:roasted-aroma', 'lexicon:clean-bitterness', 'lexicon:long-linger'],
  }),
  foodOn({
    aliases: ['구이', '구운', 'grilled', 'grill', 'broiling', 'broiling or grilling'],
    canonicalName: 'broiling or grilling',
    description: '열로 만든 구운 향과 표면 질감을 읽는 FoodOn 조리 프로세스입니다.',
    dishKindIds: ['grilled_smoked'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03450006',
    id: 'foodon-bridge:process:grilling',
    kind: 'process',
    koName: '구이',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:grilled', 'lexicon:charred-aroma'],
  }),
  foodOn({
    aliases: ['볶음', '볶은', 'stir-fry', 'stir fried', 'stir-frying', '볶기'],
    canonicalName: 'stir-frying',
    description: '짧고 강한 열로 재료를 빠르게 익혀 향과 기름감을 만드는 FoodOn 조리 프로세스입니다.',
    dishKindIds: ['grilled_smoked', 'vegetable_herb', 'meat'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03450028',
    id: 'foodon-bridge:process:stir-frying',
    kind: 'process',
    koName: '볶음',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:stir-fried', 'lexicon:pan-seared', 'lexicon:roasted-aroma'],
  }),
  foodOn({
    aliases: ['삶기', '삶은', 'boiled', 'boiling', 'boiling in container'],
    canonicalName: 'boiling in container',
    description: '끓는 물이나 액체로 재료를 익혀 수분감과 담백한 결을 만드는 FoodOn 조리 프로세스입니다.',
    dishKindIds: ['broth', 'grain_noodle', 'vegetable_herb'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03450014',
    id: 'foodon-bridge:process:boiling',
    kind: 'process',
    koName: '삶기',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:boiled', 'lexicon:tender-softness', 'lexicon:clean-finish'],
  }),
  foodOn({
    aliases: ['데침', '데친', 'blanched', 'blanching', 'food blanching'],
    canonicalName: 'food blanching',
    description: '짧게 데치고 식혀 색, 향, 식감을 보존하는 FoodOn 조리 프로세스입니다.',
    dishKindIds: ['vegetable_herb', 'cold'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03470175',
    id: 'foodon-bridge:process:blanching',
    kind: 'process',
    koName: '데침',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:boiled', 'lexicon:green-freshness', 'lexicon:clean-finish'],
  }),
  foodOn({
    aliases: ['숯불', '숯향', 'charcoal', 'charcoal broiling', '숯불 구이'],
    canonicalName: 'charcoal broiling',
    description: '직접적인 숯 열과 향으로 생기는 훈연감과 그을림을 읽는 FoodOn 조리 프로세스입니다.',
    dishKindIds: ['grilled_smoked'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03450007',
    id: 'foodon-bridge:process:charcoal-broiling',
    kind: 'process',
    koName: '숯불 구이',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:charcoal', 'lexicon:charcoal-grilled'],
  }),
  foodOn({
    aliases: ['훈연', 'smoked', 'smoking', 'food smoking', '스모크', '스모키'],
    canonicalName: 'food smoking',
    description: '연기에 노출해 향, 색, 보존성을 부여하는 FoodOn 조리/가공 프로세스입니다.',
    dishKindIds: ['grilled_smoked'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03470106',
    id: 'foodon-bridge:process:smoking',
    kind: 'process',
    koName: '훈연',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:smoked', 'lexicon:smoky-aroma'],
  }),
  foodOn({
    aliases: ['발효', 'fermented', 'fermentation', 'food fermentation', '장', '된장', '간장', '코지', '숙성'],
    canonicalName: 'food fermentation',
    description: '미생물 또는 효소 작용으로 산미, 짠맛, 감칠맛, 향의 깊이를 만드는 FoodOn 프로세스입니다.',
    dishKindIds: ['fermented_jang'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_00001304',
    id: 'foodon-bridge:process:fermentation',
    kind: 'process',
    koName: '발효',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:fermented', 'lexicon:fermented-umami', 'lexicon:fermented-aroma'],
  }),
  foodOn({
    aliases: ['절임', '피클', 'pickled', 'pickling', 'acidification', '초절임'],
    canonicalName: 'food pickling',
    description: '산 또는 염지로 재료의 산미, 염도, 리셋감을 만드는 FoodOn 가공 프로세스입니다.',
    dishKindIds: ['fermented_jang'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03460190',
    id: 'foodon-bridge:process:pickling',
    kind: 'process',
    koName: '절임',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:pickled', 'lexicon:pickled-brightness'],
  }),
  foodOn({
    aliases: ['찜', '찐', 'steamed', 'steaming', 'cooking in steam', '증기'],
    canonicalName: 'cooking in steam',
    description: '증기로 익힌 부드러운 질감과 재료 본연의 결을 읽는 FoodOn 조리 프로세스입니다.',
    dishKindIds: ['broth', 'seafood', 'vegetable_herb'],
    foodOnIri: 'http://purl.obolibrary.org/obo/FOODON_03450021',
    id: 'foodon-bridge:process:steaming',
    kind: 'process',
    koName: '찜',
    source: 'FoodOn-reference',
    sourceFacet: 'food-process',
    tbaSignalIds: ['process:steamed', 'lexicon:steamed-gentle'],
  }),
  foodOn({
    aliases: ['육수', '국물', '브로스', 'broth', 'stock', 'soup stock'],
    canonicalName: 'broth',
    description: '액체 기반의 감칠맛, 간, 여운을 읽는 조리/상품군 신호입니다.',
    dishKindIds: ['broth'],
    id: 'foodon-bridge:product:broth',
    kind: 'product-category',
    koName: '국물/브로스',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-product',
    tbaSignalIds: ['dish-kind:broth', 'process:broth', 'lexicon:clear-umami'],
  }),
  foodOn({
    aliases: ['디저트', 'dessert', '아이스크림', '타르트', '쁘띠푸르'],
    canonicalName: 'dessert',
    description: '단맛, 지방감, 산미, 온도감을 함께 읽는 후식 상품군입니다.',
    dishKindIds: ['dessert'],
    id: 'foodon-bridge:product:dessert',
    kind: 'product-category',
    koName: '디저트',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-product',
    tbaSignalIds: ['dish-kind:dessert', 'lexicon:clean-sweetness'],
  }),
  foodOn({
    aliases: ['차가운 요리', 'cold dish', 'cold', '냉', '차갑게', '아이스'],
    canonicalName: 'cold food product',
    description: '낮은 온도감이 향과 질감을 어떻게 열거나 닫는지 읽는 상품군입니다.',
    dishKindIds: ['cold'],
    id: 'foodon-bridge:product:cold-dish',
    kind: 'product-category',
    koName: '차가운 요리',
    source: 'Taste-Buddy-curated',
    sourceFacet: 'food-product',
    tbaSignalIds: ['dish-kind:cold', 'lexicon:cool-snap'],
  }),
];

export const TBA_FOODON_BRIDGE_BY_ID: Readonly<Record<string, TbaFoodOntologyBridgeEntry>> = Object.fromEntries(
  TBA_FOODON_BRIDGE_ENTRIES.map((entry) => [entry.id, entry]),
);
