import { DISH_KIND_OPTIONS } from './dishKindTags';
import { TASTE_IDS } from './designTokens';
import { TBA_CORE_TASTE_LEXICON } from './tbaCoreTasteLexicon';
import type { TasteId } from './designTokens';
import type {
  TbaCanonicalDishKindId,
  TbaCoreTasteLexiconCategory,
  TbaCoreTasteLexiconEntry,
} from '../types/tasteBuddyKnowledge';
import type { TbaSignalDefinition, TbaSignalDomain } from '../types/tbaSignals';
import {
  PERCEPTUAL_AXES,
  type PerceptualAxis,
} from '../types/tastePersonalization';

const LEXICON_TASTE_BUBBLE_CATEGORIES: readonly TbaCoreTasteLexiconCategory[] = [
  'composition',
  'ingredient',
  'taste',
];

function getDominantAxis<TAxis extends string>(
  vector: Partial<Record<TAxis, number>>,
  axes: readonly TAxis[],
) {
  return axes
    .map((axis) => ({
      axis,
      weight: Math.abs(vector[axis] ?? 0),
    }))
    .filter((candidate) => candidate.weight > 0.001)
    .sort((left, right) => right.weight - left.weight)[0]?.axis;
}

function getLexiconSignalDomain(entry: TbaCoreTasteLexiconEntry): TbaSignalDomain {
  return LEXICON_TASTE_BUBBLE_CATEGORIES.includes(entry.category)
    ? 'taste-bubble'
    : 'perceptual-detail';
}

function getLexiconSignalStatus(entry: TbaCoreTasteLexiconEntry): TbaSignalDefinition['status'] {
  if (entry.status === 'retired') {
    return 'retired';
  }

  return entry.status === 'active' || entry.status === 'human-reviewed'
    ? 'active'
    : 'candidate';
}

export const TBA_DISH_KIND_SIGNALS: readonly TbaSignalDefinition[] = DISH_KIND_OPTIONS.map((option) => ({
  aliases: [option.id, option.label, ...option.keywords],
  canonicalDishKindId: option.id as TbaCanonicalDishKindId,
  confidence: 0.92,
  description: `${option.label} 계열 메뉴를 TBA의 canonical dish kind로 읽기 위한 신호입니다.`,
  domain: 'dish-kind',
  id: `dish-kind:${option.id}`,
  label: option.label,
  status: 'active',
}));

export const TBA_INGREDIENT_KIND_SIGNALS: readonly TbaSignalDefinition[] = [
  {
    aliases: ['흰살생선', 'white fish', '생선', '도미', '광어', '농어'],
    canonicalDishKindId: 'seafood',
    confidence: 0.74,
    description: '기름이 가볍고 맑은 감칠맛과 결을 중심으로 읽는 생선 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:white-fish',
    label: '흰살 생선',
    parentIds: ['dish-kind:seafood'],
    status: 'active',
  },
  {
    aliases: ['기름진 생선', '등푸른 생선', 'oily fish', '고등어', '방어', '참치'],
    canonicalDishKindId: 'seafood',
    confidence: 0.7,
    description: '지방감과 선명한 해산물 향이 함께 올라오는 생선 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:oily-fish',
    label: '기름진 생선',
    parentIds: ['dish-kind:seafood'],
    status: 'active',
  },
  {
    aliases: ['조개', '패류', 'shellfish', '굴', '가리비', '백합'],
    canonicalDishKindId: 'seafood',
    confidence: 0.76,
    description: '해수 감칠맛과 은근한 단맛을 함께 읽는 패류 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:shellfish',
    label: '패류',
    parentIds: ['dish-kind:seafood'],
    status: 'active',
  },
  {
    aliases: ['갑각류', 'crustacean', '새우', '게', '랍스터'],
    canonicalDishKindId: 'seafood',
    confidence: 0.76,
    description: '갑각류 특유의 단맛, 향, 감칠맛을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:crustacean',
    label: '갑각류',
    parentIds: ['dish-kind:seafood'],
    status: 'active',
  },
  {
    aliases: ['소고기', '한우', 'beef', '채끝', '안심', '등심'],
    canonicalDishKindId: 'meat',
    confidence: 0.78,
    description: '육향, 지방감, 감칠맛의 밀도를 읽는 소고기 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:beef',
    label: '소고기',
    parentIds: ['dish-kind:meat'],
    status: 'active',
  },
  {
    aliases: ['돼지고기', 'pork', '삼겹', '목살', '돼지'],
    canonicalDishKindId: 'meat',
    confidence: 0.72,
    description: '돼지고기의 지방감, 단맛, 구운 향을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:pork',
    label: '돼지고기',
    parentIds: ['dish-kind:meat'],
    status: 'active',
  },
  {
    aliases: ['양고기', '양갈비', 'lamb'],
    canonicalDishKindId: 'meat',
    confidence: 0.7,
    description: '양고기의 향, 지방감, 허브/훈연과의 결합을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:lamb',
    label: '양고기',
    parentIds: ['dish-kind:meat'],
    status: 'active',
  },
  {
    aliases: ['가금류', '닭', '오리', 'poultry', 'duck', 'chicken'],
    canonicalDishKindId: 'meat',
    confidence: 0.72,
    description: '닭과 오리처럼 육향이 비교적 섬세한 가금류 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:poultry',
    label: '가금류',
    parentIds: ['dish-kind:meat'],
    status: 'active',
  },
  {
    aliases: ['버섯', 'mushroom', '표고', '송이', '트러플'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.72,
    description: '흙내, 구수함, 감칠맛의 낮은 층을 읽는 버섯 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:mushroom',
    label: '버섯',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['잎채소', 'leafy green', '나물', '봄동', '허브', '샐러드'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.72,
    description: '초록 향, 쌉싸름함, 산뜻한 질감을 읽는 잎채소 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:leafy-green',
    label: '잎채소',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['뿌리채소', 'root vegetable', '더덕', '무', '당근', '비트'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.68,
    description: '흙내, 단맛, 구운 향을 함께 읽는 뿌리채소 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:root-vegetable',
    label: '뿌리채소',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['곡물', 'grain', '쌀', '보리', '메밀', '빵'],
    canonicalDishKindId: 'grain_noodle',
    confidence: 0.7,
    description: '구수함, 전분감, 포만감의 바닥을 읽는 곡물 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:grain',
    label: '곡물',
    parentIds: ['dish-kind:grain_noodle'],
    status: 'active',
  },
  {
    aliases: ['면', 'noodle', '파스타', '국수', '카펠리니'],
    canonicalDishKindId: 'grain_noodle',
    confidence: 0.7,
    description: '면의 탄력, 온도감, 소스 흡착을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:noodle',
    label: '면',
    parentIds: ['dish-kind:grain_noodle'],
    status: 'active',
  },
  {
    aliases: ['과일', 'fruit', '오미자', '감귤', '딸기', '배'],
    canonicalDishKindId: 'dessert',
    confidence: 0.72,
    description: '과일 향, 산미, 단맛의 균형을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:fruit',
    label: '과일',
    parentIds: ['dish-kind:dessert'],
    status: 'active',
  },
  {
    aliases: ['유제품', 'dairy', '크림', '치즈', '요거트', '버터'],
    canonicalDishKindId: 'dairy_cheese',
    confidence: 0.7,
    description: '유제품의 지방감, 산미, 부드러운 질감을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:dairy',
    label: '유제품',
    parentIds: ['dish-kind:dairy_cheese'],
    status: 'active',
  },
  {
    aliases: ['초콜릿', 'chocolate', '카카오', '코코아'],
    canonicalDishKindId: 'dessert',
    confidence: 0.72,
    description: '초콜릿의 쓴단맛과 지방감, 긴 여운을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:chocolate',
    label: '초콜릿',
    parentIds: ['dish-kind:dessert'],
    status: 'active',
  },
  {
    aliases: ['차', 'tea', '티', '우롱', '녹차', '홍차'],
    canonicalDishKindId: 'beverage_pairing',
    confidence: 0.68,
    description: '차의 향, 쌉싸름함, 페어링 후미를 읽는 음료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:tea',
    label: '차',
    parentIds: ['dish-kind:beverage_pairing'],
    status: 'active',
  },
  {
    aliases: ['달걀', '계란', 'egg', '노른자', '흰자'],
    confidence: 0.7,
    description: '달걀의 부드러운 지방감, 둥근 단맛, 유화감을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:egg',
    label: '달걀',
    status: 'active',
  },
  {
    aliases: ['두부', '콩', 'soy', 'tofu', '콩물', '두유'],
    canonicalDishKindId: 'legume_tofu',
    confidence: 0.7,
    description: '콩과 두부의 담백한 고소함, 부드러운 결, 낮은 감칠맛을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:soy-tofu',
    label: '콩/두부',
    parentIds: ['dish-kind:legume_tofu'],
    status: 'active',
  },
  {
    aliases: ['오징어', '문어', '한치', '낙지', 'squid', 'octopus', 'cephalopod'],
    canonicalDishKindId: 'seafood',
    confidence: 0.72,
    description: '두족류의 탄력, 해산물 감칠맛, 깨끗한 짠맛을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:cephalopod',
    label: '오징어/문어',
    parentIds: ['dish-kind:seafood'],
    status: 'active',
  },
  {
    aliases: ['해조류', '김', '다시마', '미역', 'seaweed', 'kelp'],
    canonicalDishKindId: 'seafood',
    confidence: 0.72,
    description: '해조류의 바다 향, 미네랄 짠맛, 맑은 감칠맛을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:seaweed',
    label: '해조류',
    parentIds: ['dish-kind:seafood'],
    status: 'active',
  },
  {
    aliases: ['마늘', '양파', '대파', '쪽파', 'allium', 'garlic', 'onion', 'scallion'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.7,
    description: '마늘, 양파, 파의 향, 단맛, 열감 변화를 읽는 향채 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:allium',
    label: '마늘/양파류',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['토마토', 'tomato', '방울토마토'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.68,
    description: '토마토의 산미, 감칠맛, 과실 단맛을 함께 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:tomato',
    label: '토마토',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['감자', '고구마', '전분', 'potato', 'sweet potato', 'starch'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.68,
    description: '감자와 전분류의 포슬함, 단맛, 포만감을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:potato-starch',
    label: '감자/전분류',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['양배추', '배추', '브로콜리', '콜리플라워', 'cabbage', 'brassica'],
    canonicalDishKindId: 'vegetable_herb',
    confidence: 0.66,
    description: '배추와 양배추류의 단맛, 풋내, 익혔을 때의 부드러운 향을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:brassica',
    label: '배추/양배추류',
    parentIds: ['dish-kind:vegetable_herb'],
    status: 'active',
  },
  {
    aliases: ['쌀', '밥', 'rice', '누룽지', '리조또'],
    canonicalDishKindId: 'grain_noodle',
    confidence: 0.72,
    description: '쌀의 전분감, 단맛, 구수한 깊이를 읽는 곡물 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:rice',
    label: '쌀',
    parentIds: ['dish-kind:grain_noodle'],
    status: 'active',
  },
  {
    aliases: ['밀', '밀가루', '빵', '면', 'wheat', 'flour', 'bread'],
    canonicalDishKindId: 'grain_noodle',
    confidence: 0.68,
    description: '밀 기반 음식의 탄력, 고소함, 구운 향을 읽는 곡물 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:wheat',
    label: '밀',
    parentIds: ['dish-kind:grain_noodle'],
    status: 'active',
  },
  {
    aliases: ['견과', '깨', '참깨', '들깨', 'nut', 'seed', 'sesame', 'perilla'],
    confidence: 0.72,
    description: '견과와 씨앗류의 고소한 향, 지방감, 긴 여운을 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:nut-seed',
    label: '견과/씨앗',
    status: 'active',
  },
  {
    aliases: ['참기름', '들기름', 'sesame oil', 'perilla oil'],
    confidence: 0.7,
    description: '씨앗 기름의 고소한 향, 지방 코팅감, 후미를 읽는 재료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:seed-oil',
    label: '참기름/들기름',
    status: 'active',
  },
  {
    aliases: ['간장', '된장', '미소', 'soy sauce', 'doenjang', 'miso'],
    canonicalDishKindId: 'fermented_jang',
    confidence: 0.76,
    description: '간장과 된장의 발효 감칠맛, 짠맛, 장 향을 읽는 양념 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:soy-jang',
    label: '간장/된장',
    parentIds: ['dish-kind:fermented_jang'],
    status: 'active',
  },
  {
    aliases: ['고추장', '고춧가루', '마파', '사천', 'gochujang', 'chili paste', 'chili powder', 'mapo', 'sichuan'],
    canonicalDishKindId: 'spice_heat',
    confidence: 0.72,
    description: '고추장의 발효 감칠맛, 단맛, 매운 열감을 함께 읽는 양념 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:chili-jang',
    label: '고추장/고추',
    parentIds: ['dish-kind:spice_heat', 'dish-kind:fermented_jang'],
    status: 'active',
  },
  {
    aliases: ['식초', '초', 'vinegar', 'acid seasoning'],
    confidence: 0.68,
    description: '식초의 산미, 절임감, 입안을 정리하는 효과를 읽는 양념 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:vinegar',
    status: 'active',
    label: '식초',
  },
  {
    aliases: ['커피', 'coffee', '에스프레소', '콜드브루'],
    canonicalDishKindId: 'beverage_pairing',
    confidence: 0.68,
    description: '커피의 볶은 향, 쓴맛, 산미, 긴 여운을 읽는 음료 신호입니다.',
    domain: 'ingredient-kind',
    id: 'ingredient:coffee',
    label: '커피',
    parentIds: ['dish-kind:beverage_pairing'],
    status: 'active',
  },
];

export const TBA_COOKING_PROCESS_SIGNALS: readonly TbaSignalDefinition[] = [
  {
    aliases: ['날것', '회', 'raw', 'cured', '절임', '숙성회'],
    canonicalDishKindId: 'raw_cured',
    confidence: 0.7,
    description: '열을 크게 쓰지 않은 재료의 투명도와 산미/염도를 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:raw-cured',
    label: '생/절임',
    parentIds: ['dish-kind:raw_cured'],
    status: 'active',
  },
  {
    aliases: ['찜', '찐', 'steamed', '증기'],
    canonicalDishKindId: 'steamed_braised',
    confidence: 0.68,
    description: '증기로 익힌 부드러운 질감과 재료 본연의 결을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:steamed',
    label: '찜',
    parentIds: ['dish-kind:steamed_braised'],
    status: 'active',
  },
  {
    aliases: ['육수', '국물', '브로스', 'broth', 'stock'],
    canonicalDishKindId: 'broth',
    confidence: 0.76,
    description: '액체 기반의 감칠맛, 간, 여운을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:broth',
    label: '육수',
    parentIds: ['dish-kind:broth'],
    status: 'active',
  },
  {
    aliases: ['구이', '구운', 'grilled', 'grill'],
    canonicalDishKindId: 'grilled_smoked',
    confidence: 0.76,
    description: '열로 만든 구운 향과 표면 질감을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:grilled',
    label: '구이',
    parentIds: ['dish-kind:grilled_smoked'],
    status: 'active',
  },
  {
    aliases: ['숯불', '숯향', 'charcoal', '숯불 구이'],
    canonicalDishKindId: 'grilled_smoked',
    confidence: 0.78,
    description: '숯불에서 오는 훈연감, 그을림, 감칠맛을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:charcoal',
    label: '숯불',
    parentIds: ['dish-kind:grilled_smoked'],
    status: 'active',
  },
  {
    aliases: ['훈연', 'smoked', '스모크', '스모키'],
    canonicalDishKindId: 'grilled_smoked',
    confidence: 0.78,
    description: '연기 향과 그 향이 남기는 긴 여운을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:smoked',
    label: '훈연',
    parentIds: ['dish-kind:grilled_smoked'],
    status: 'active',
  },
  {
    aliases: ['튀김', 'fried', '프라이', '크리스피'],
    canonicalDishKindId: 'fried_crispy',
    confidence: 0.68,
    description: '바삭한 표면, 기름감, 온도감을 함께 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:fried',
    label: '튀김',
    parentIds: ['dish-kind:fried_crispy'],
    status: 'active',
  },
  {
    aliases: ['볶음', '볶은', 'stir-fry', 'stir fried', '볶기'],
    canonicalDishKindId: 'stir_fried_wok',
    confidence: 0.68,
    description: '짧고 강한 열로 만든 향, 기름감, 재료 표면의 집중도를 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:stir-fried',
    label: '볶음',
    parentIds: ['dish-kind:stir_fried_wok'],
    status: 'active',
  },
  {
    aliases: ['삶기', '삶은', 'boiled', 'boiling', '데침', 'blanched'],
    confidence: 0.66,
    description: '물로 익힌 재료의 부드러운 결, 수분감, 담백한 마무리를 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:boiled',
    label: '삶기/데침',
    status: 'active',
  },
  {
    aliases: ['조림', '브레이즈', 'braised', '졸임'],
    canonicalDishKindId: 'steamed_braised',
    confidence: 0.66,
    description: '농축된 소스와 부드러운 질감, 긴 여운을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:braised',
    label: '조림',
    parentIds: ['dish-kind:steamed_braised'],
    status: 'active',
  },
  {
    aliases: ['로스팅', 'roasted', '구운 채소', '오븐'],
    confidence: 0.66,
    description: '로스팅으로 만든 단맛, 고소함, 갈색 향을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:roasted',
    label: '로스팅',
    parentIds: ['dish-kind:grilled_smoked'],
    status: 'active',
  },
  {
    aliases: ['발효', 'fermented', '장', '된장', '간장', '코지', '숙성'],
    canonicalDishKindId: 'fermented_jang',
    confidence: 0.8,
    description: '발효에서 오는 산미, 짠맛, 감칠맛과 향의 깊이를 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:fermented',
    label: '발효',
    parentIds: ['dish-kind:fermented_jang'],
    status: 'active',
  },
  {
    aliases: ['피클', 'pickled', '절임', '초절임'],
    canonicalDishKindId: 'raw_cured',
    confidence: 0.68,
    description: '절임이 만드는 산미, 염도, 리셋감을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:pickled',
    label: '절임',
    parentIds: ['dish-kind:raw_cured'],
    status: 'active',
  },
  {
    aliases: ['우린', '인퓨전', 'infused', '향을 입힌'],
    confidence: 0.62,
    description: '재료 향을 액체나 지방에 옮긴 은은한 향 신호입니다.',
    domain: 'cooking-process',
    id: 'process:infused',
    label: '인퓨전',
    status: 'candidate',
  },
  {
    aliases: ['졸인', '리덕션', 'reduced', '농축'],
    canonicalDishKindId: 'sauce_glaze',
    confidence: 0.64,
    description: '소스를 졸이며 만든 농도와 여운을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:reduced',
    label: '리덕션',
    parentIds: ['dish-kind:sauce_glaze'],
    status: 'candidate',
  },
  {
    aliases: ['에멀전', 'emulsified', '유화', '오일 소스'],
    canonicalDishKindId: 'sauce_glaze',
    confidence: 0.62,
    description: '지방과 액체가 만든 질감, 광택, 산미 정렬을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:emulsified',
    label: '유화',
    parentIds: ['dish-kind:sauce_glaze'],
    status: 'candidate',
  },
  {
    aliases: ['저온', '수비드', 'low temp', 'low-temperature', '저온 조리'],
    confidence: 0.62,
    description: '낮은 온도로 만든 부드러운 결, 수분감, 온도감을 읽는 조리 신호입니다.',
    domain: 'cooking-process',
    id: 'process:low-temp',
    label: '저온 조리',
    status: 'candidate',
  },
];

export const TBA_INTENSITY_SIGNALS: readonly TbaSignalDefinition[] = [
  {
    aliases: ['은은함', 'subtle', '섬세함', '약한'],
    confidence: 0.7,
    description: '감각이 낮은 강도로 조용히 읽히는 신호입니다.',
    domain: 'intensity',
    id: 'intensity:subtle',
    intensityValue: 0.22,
    label: '은은함',
    status: 'active',
  },
  {
    aliases: ['균형', 'balanced', '적당함', '잘 맞음'],
    confidence: 0.76,
    description: '강도와 방향이 안정적으로 맞는 신호입니다.',
    domain: 'intensity',
    id: 'intensity:balanced',
    intensityValue: 0.5,
    label: '균형',
    status: 'active',
  },
  {
    aliases: ['선명함', 'clear', '뚜렷함', '명확함'],
    confidence: 0.76,
    description: '감각의 윤곽이 흐리지 않고 선명하게 읽히는 신호입니다.',
    domain: 'intensity',
    id: 'intensity:clear',
    intensityValue: 0.68,
    label: '선명함',
    status: 'active',
  },
  {
    aliases: ['강함', 'strong', '진함', '농도감'],
    confidence: 0.7,
    description: '감각의 밀도와 존재감이 높은 신호입니다.',
    domain: 'intensity',
    id: 'intensity:strong',
    intensityValue: 0.82,
    label: '강함',
    status: 'active',
  },
  {
    aliases: ['과함', 'overwhelming', '부담', '피로함'],
    confidence: 0.66,
    description: '강도가 높아 피로감이나 과한 인상으로 이어질 수 있는 신호입니다.',
    domain: 'intensity',
    id: 'intensity:overwhelming',
    intensityValue: 1,
    label: '과함',
    status: 'active',
  },
];

export const TBA_SENTIMENT_SIGNALS: readonly TbaSignalDefinition[] = [
  {
    aliases: ['좋음', 'liked', '마음에 듦', '만족'],
    confidence: 0.7,
    description: '사용자가 긍정적으로 받아들인 취향 반응 신호입니다.',
    domain: 'sentiment',
    id: 'sentiment:liked',
    label: '좋았음',
    sentimentValue: 1,
    status: 'active',
  },
  {
    aliases: ['보통', 'neutral', '무난함'],
    confidence: 0.62,
    description: '선호와 비선호가 강하게 갈리지 않은 반응 신호입니다.',
    domain: 'sentiment',
    id: 'sentiment:neutral',
    label: '무난함',
    sentimentValue: 0,
    status: 'active',
  },
  {
    aliases: ['과함', 'too much', '너무 강함', '부담스러움'],
    confidence: 0.66,
    description: '감각이 취향 대비 과하게 읽힌 반응 신호입니다.',
    domain: 'sentiment',
    id: 'sentiment:too-much',
    label: '과했음',
    sentimentValue: -1,
    status: 'active',
  },
  {
    aliases: ['약함', 'weak', '아쉬움', '흐림'],
    confidence: 0.62,
    description: '기대한 감각이 충분히 읽히지 않은 반응 신호입니다.',
    domain: 'sentiment',
    id: 'sentiment:weak',
    label: '아쉬움',
    sentimentValue: -1,
    status: 'active',
  },
  {
    aliases: ['피로함', 'tiring', '물림', '무거움'],
    confidence: 0.62,
    description: '후반부에 감각 피로가 생긴 반응 신호입니다.',
    domain: 'sentiment',
    id: 'sentiment:tiring',
    label: '피로감',
    sentimentValue: -1,
    status: 'active',
  },
  {
    aliases: ['다시 먹고 싶음', 'wants again', '재방문', '또 먹고 싶음'],
    confidence: 0.68,
    description: '다음 경험으로 이어질 가능성이 높은 강한 긍정 반응 신호입니다.',
    domain: 'sentiment',
    id: 'sentiment:wants-again',
    label: '다시 찾고 싶음',
    sentimentValue: 1,
    status: 'active',
  },
];

export const TBA_CORE_LEXICON_SIGNALS: readonly TbaSignalDefinition[] = TBA_CORE_TASTE_LEXICON.map((entry) => ({
  aliases: [entry.id, entry.label, ...entry.aliases],
  confidence: entry.initialConfidence,
  description: entry.summary,
  domain: getLexiconSignalDomain(entry),
  id: `lexicon:${entry.id}`,
  label: entry.label,
  lexiconCategory: entry.category,
  lexiconIds: [entry.id],
  perceptualAxis: getDominantAxis(entry.perceptualVector, PERCEPTUAL_AXES),
  status: getLexiconSignalStatus(entry),
  tasteAxis: getDominantAxis(entry.tasteVector, TASTE_IDS as readonly TasteId[]),
}));

export const TBA_SIGNAL_TAXONOMY: readonly TbaSignalDefinition[] = [
  ...TBA_DISH_KIND_SIGNALS,
  ...TBA_INGREDIENT_KIND_SIGNALS,
  ...TBA_COOKING_PROCESS_SIGNALS,
  ...TBA_INTENSITY_SIGNALS,
  ...TBA_SENTIMENT_SIGNALS,
  ...TBA_CORE_LEXICON_SIGNALS,
];

export const TBA_SIGNAL_BY_ID: Readonly<Record<string, TbaSignalDefinition>> = Object.fromEntries(
  TBA_SIGNAL_TAXONOMY.map((definition) => [definition.id, definition]),
);
